### ISSUE TITLE
Extractor not working, requires glibc

### ISSUE THREAD

**Issue by rix1337** [jlesage/docker-jdownloader-2#1]
Thanks for supporting this. I have just noticed, that the builtin extractor is not working. Some googlefu later and we have this:

https://github.com/Mumie-hub/docker-services/blob/master/jdownloader/Dockerfile

As mumiehub describes here:
https://hub.docker.com/r/mumiehub/jdownloader/

** glibc is added for extraction to work**

**Comment by jlesage** [comment]
Thanks for reporting this issue.  I'm already working on a fix :)

**Comment by rix1337** [comment]
You are great!

**Comment by rix1337** [comment]
7435e7e6e9e5c0045475cb421e36e70c4849f73c

What a great insight you have. No way I would have been able to trace and fix it to this depht! Thanks for not only making, but actively supporting this.

**Comment by rix1337** [comment]
Workaround confirmed working!

**Comment by jlesage** [comment]
Thanks for confirming that it's working!
