### ISSUE TITLE
Server Disconnected (Code :1006) Docker on Synology DSM 7.01

### ISSUE THREAD

**Issue by prco71** [jlesage/docker-jdownloader-2#100]
Hi,

I am using a Synology DS918+ all with the latest DSM and latest Docker app.

I had JDownloader working but then all of a sudden the JDownloader webpage would not display anymore.  the header was there and it said "Server Disconnected (code: 1006)" .

I have tried various settings and ports without success.  I ultimately deleted the contained and started from scratch.  Same problem.  Disable the SECURE_CONNECTION and it works.

I have the three standard ports in the container.  

Not sure what to do.

Thanks

**Comment by jlesage** [comment]
This error is usually fixed by clearing your browser's cache.  You can also try to connect in an incognito/private window.

**Comment by jlesage** [comment]
Closing the issue.  Please re-open if needed.
