### ISSUE TITLE
Is there any way to reduce overhead?

### ISSUE THREAD

**Issue by jaxjexjox** [jlesage/docker-jdownloader-2#101]
I've just run the tool, glances on my dockerVM and I can see jdownloader really taking the cake when it comes to utilisation of processor.

docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host --network host -it nicolargo/glances:3.2.0-full

I do realise it is rendering an actual GUI for me which is nice, but is it possible to 'park' itself into some kind of sleep mode?

**Comment by jlesage** [comment]
Did you check which process of the container is taking most of the CPU ?  My guest is that it's JDownloader itself and not the UI.

> is it possible to 'park' itself into some kind of sleep mode

Are you talking about the container ?  You can always stop the container when not used and start it when needed.

**Comment by jlesage** [comment]
Closing this issue, please re-open if needed.

Note that with the latest image, it's possible to run JDownloader in headless mode.
