### ISSUE TITLE
Font issue with Chinese an other foreign characters

### ISSUE THREAD

**Issue by XiaoKe89** [jlesage/docker-jdownloader-2#102]
So I was having issues with downloading videos that had Chinese characters in the title I was checking with jdownloader support and they said it is due to not having the right font package installed. They were saying you would need to update the container font packages for those to display properly.
I also tested Japanese which does not display properly.

Here is what support sent me:

"You will have to update/customize this container to also contain full
font environment. Looks like Java just as access to its minimal set of fonts bundled with java itself
Better check/ask with the docker maintainer to fix this by installing a font package(eg fontconfig)
Java will automatic pick up correct font and working out of the box"

**Comment by jlesage** [comment]
Did you setup the `ENABLE_CJK_FONT` environment variable ?
https://github.com/jlesage/docker-jdownloader-2#environment-variables

**Comment by XiaoKe89** [comment]
So that was exactly what needed to be done, just added a new variable using the Variable name of: ENABLE_CJK_FONT and set it to 1 and that resolved the issue. Thanks for pointing me in the right direction!
