### ISSUE TITLE
How to add packages to container?

### ISSUE THREAD

**Issue by AlexeiScherbakov** [jlesage/docker-jdownloader-2#103]
I want to troubleshoot connection issues and I need to install packages to jd2 docker container, but 'apt','apt-get','app-pkg' commands are missing. How I can install 'speedtest-cli' into container?

**Comment by AlexeiScherbakov** [comment]
This image use 'apk' - please add this to doc :-)

**Comment by jlesage** [comment]
Packages can be installed via the `INSTALL_PACKAGES` environment variable.  This is the method users should use.
See https://github.com/jlesage/docker-jdownloader-2#environment-variables
