### ISSUE TITLE
Document rar5 beta support

### ISSUE THREAD

**Issue by jlesage** [jlesage/docker-jdownloader-2#11]
A section in the README should be added do document how to add (beta) support for rar5 format.

See https://board.jdownloader.org/showthread.php?t=71069 and  https://lime-technology.com/forums/topic/58552-support-djoss-jdownloader-2/?do=findComment&comment=637196

**Comment by fightforlife** [comment]
Could this be integrated into the image?
It is just adding two files and would really help!

**Comment by jlesage** [comment]
Closing issue, RAR5 is now properly supported by JDownloader.
