### ISSUE TITLE
Can't activate account

### ISSUE THREAD

**Issue by S-Line21** [jlesage/docker-jdownloader-2#110]
Using on DS718+ everything works fine except when adding an account (ddownload). After entering user and pass I got message "captcha required" and account is not usable.

**Comment by jlesage** [comment]
For accounts that require captcha, you can use the MyJDownloader browser plugin to add them.

**Comment by S-Line21** [comment]
ok, will try, thank you

**Comment by jlesage** [comment]
Ok perfect.  Please re-open the issue if needed.
