### ISSUE TITLE
Only accessible via MyJdownloader

### ISSUE THREAD

**Issue by Scarpall** [jlesage/docker-jdownloader-2#111]
Hi Since this week my Container only is accessible via MyJdownloader.
I already createt a new one but same problem with the newest image.
Access via WebBrowser did never work.
always this error: 
27/10/2022 22:10:41 Got connection from client 192.168.2.21
27/10/2022 22:10:41   other clients:
27/10/2022 22:10:41 Got 'ws' WebSockets handshake
27/10/2022 22:10:41 webSocketsHandshake: incomplete client handshake

VNC did work but since this week its always this message instantly:
Server disconnected Code: 1006

**Comment by jlesage** [comment]
This is usually fixed by clearing your browser's cache.
To confirm this is a cache problem, you can try with a different browser and/or with an incognito/private window.

**Comment by Scarpall** [comment]
Yeah after cache clearing the VNC connection works again.
Do i need to configure something special to use the web interface? cause i was reading that there is the option to use browser, vnc or myJdownloader

**Comment by jlesage** [comment]
After clearing the cache, it's the web interface that should work again.  Is it the case ?

**Comment by Scarpall** [comment]
i can access the vnc web interface and it works.
i was understanding it wrong i guess.
i thought 1 option is vnc/vnc - webinterface, 1 option myjdownloader and 1 additional web option

**Comment by jlesage** [comment]
Ok I see.  So yes there are 3 options:
- VNC
- VNC through web browser
- MyJDownloader

**Comment by Scarpall** [comment]
okay then thanks for the suggestion to clear the cache. this worked fine
