### ISSUE TITLE
Setting jdownloader 2 for QNAP 253B

### ISSUE THREAD

**Issue by Badaw971** [jlesage/docker-jdownloader-2#113]
Hello,

I have a problem, so far the program works fine except I need to change the download folder which is on another hard drive of my QNAP 253B NAS.

The source folder
Hard disk 1/Container/output
I would like the files to be uploaded to the following folder
Hard disk 2 /Download

Could you tell me the steps or file to modify to achieve this?

Thank you for your help.

**Comment by jlesage** [comment]
If you are using the Container Station to create the container, you just need to specify a "Shared Folder", where the host folder is `/Download` and the container folder is `/output`.

**Comment by jlesage** [comment]
Sorry, I'm not sure to understand what you are trying to say.  Could you share the settings of your container ?

With what I said in my previous comment, the `/output` folder inside the container will be mapped to your "Hard disk N°2 / Download" folder.  This means that in JDownloader, everything downloaded to `/output` will end up in your "Hard disk N°2 / Download" folder.

**Comment by Badaw971** [comment]
Hello,
thank you for your answer, you are right with a screen it will be easier.
The /output must be in the second hard drive or I could access any folder. If this is not possible then only in the directory hard disk 2 /Shared Videos/Télécharger #
![voulu](https://user-images.githubusercontent.com/117314246/200111610-cf199dd5-e736-4782-bc22-e926fd1947c9.png)

**Comment by jlesage** [comment]
Ok, then in the `Container Station`, can you set a shared folder that maps `/output` to `/ Shared Videos/Télécharger` ?

Here is a random example I found to show you what I'm talking about:

![](https://i.stack.imgur.com/bJ0NU.png)

**Comment by Badaw971** [comment]
I can't modify anything, everything is blocked.
![Capture d’écran 2022-11-08 052424](https://user-images.githubusercontent.com/117314246/200474783-0701423a-9d11-49d3-8d9a-12f4d7ea3e4c.png)

**Comment by jlesage** [comment]
Same thing if the container is stopped ?

I'm not a QNAP user, but you may have to delete the container and re-create it.  Note that even `/config` doesn't seem to be mapped correctly.

**Comment by Badaw971** [comment]
unfortunately even by stopping the docker I cannot modify it. Is it possible to modify the configuration file?
I'm not a programming expert how can I recreate the docker? Is there a particular setting to do?

**Comment by Badaw971** [comment]
I understand, I had a permission problem. Which file should I modify to put the correct path?

**Comment by Badaw971** [comment]
can I modify the file in this location?
![fichier config](https://user-images.githubusercontent.com/117314246/200486381-abcec0e2-f145-4b0a-82cf-6022d9546fa4.png)
![dossier config](https://user-images.githubusercontent.com/117314246/200486385-a24070a0-fa63-468c-a22f-d919c831b1b7.png)

I put the config file just in case.
Thanks in advance

**Comment by Badaw971** [comment]
I finally succeeded, I had to delete the application and install it again. Thank you for taking the time to explain to me how to install it.
Anyway great job! Thanks again ;)

**Comment by jlesage** [comment]
If you use the Container Station, you need to use the UI to manage the container.  The other way is to not use it and instead use shell and run `docker` commands yourself.

Happy to know that you were able to install it!
