### ISSUE TITLE
Upper Menu Bar (for clipboard, etc) is gone after update. How to get it back?

### ISSUE THREAD

**Issue by gitttt54** [jlesage/docker-jdownloader-2#116]
Hello,

I'm using this container a long time and the topmost VNC navigation, where users could easily reach the clipboard content has now moved to a 3 dot hidden menu on the left of the screen.

This is very inconvenient and cumbersome to use, if users need use the clipboard option very often, which I do.

I'l looking for a switch to move that clipboard button to the top again.

How would I set this up?

Thank you :-) 

Old:
<img width="1476" alt="Bildschirmfoto 2022-11-19 um 02 04 01" src="https://user-images.githubusercontent.com/96403800/202826399-12c8176d-1ebe-4bc4-849f-3fb313e71020.png">

New:
<img width="421" alt="Bildschirmfoto 2022-11-19 um 02 02 33" src="https://user-images.githubusercontent.com/96403800/202826408-e9e0c2ed-cfae-4f3f-9fe0-e553df76442c.png">

**Comment by jlesage** [comment]
How the new method is inconvenient ?  Clipboard is 1-click away in both cases.

You can always stick the previous version by using the `v1.7.2` Docker image tag.  So instead of creating the container using `jlesage/jdownloader-2`, use `jlesage/jdownloader-2:v1.7.2`.

**Comment by gitttt54** [comment]
its cumbersome because I'm on mac and my (autohidden) dock is on the left side of the monitor too.
so, each time, I try to reach that 3 dot menu, in 90% the trackpad moves 1 pixel to far and the dock opens, which then hides the part of my browser, where the 3 dot menu is.
Also more clicks are needed now:
old: 1 click to open the clipboard, curser was already in the textbox, so I could just paste the content and click "submit".
now its 2 clicks more to focus the clipboard and to close the 3 dot menu again, which also hides too much of my screen. I can not read the content of my tabs while typing or pasting to the clipboard.
That might sound nitpicking, but it is my workflow and it has proven fast and flexible. 
this sadly, is now no more.

I have reverted to the previous version, but I thought, it might be possible to switch between two modes.

Thank you for that great and useful container!

**Comment by jlesage** [comment]
I don't think the old UI will come back.  However, the new one can be improved.

> old: 1 click to open the clipboard, curser was already in the textbox, so I could just paste the content and click "submit".
now its 2 clicks more to focus the clipboard and to close the 3 dot menu again

So it seems that adding auto focusing on the clipboard text box would solve this issue: first click on the 3 dots, fill the content of the clipboard, then second click to close the menu.

> which also hides too much of my screen

You can collapse the Settings section to make the menu smaller.

> I can not read the content of my tabs while typing or pasting to the clipboard.

Because of the new position of the menu ?  The old Clipboard box was also taking a similar amount of space.

**Comment by oystermon** [comment]
Hi jlesage,

First of all thanks for making this docker container.. have been using it a lot the past few years..

I agree with gittt54 that it feels a bit less straightforward than the previous version..

- The old version used to have a submit button - i think you mentioned the current way is to click on the three dots after pasting? would be nice to have the button back if possible :)
- It would be nice to have the three dots/menu on the right hand side of the screen, because currently it blocks stuff more if it's on the left

other than that I think it's fine.. 👍

**Comment by jlesage** [comment]
A submit button is not needed.  What you type in the clipboard is automatically and instantly available to the app.  So closing the menu is not required for the content to be available.

I don't know if you noticed, but you can move the 3 dots up and down.

Finally, having the choice of the location of the 3 dots (left or right side) might be something possible.  I will look at this.

**Comment by oystermon** [comment]
Thanks for the prompt reply - I just tried it and it seems to have automatically added it ok..

Yes I realised I can move it up or down which is nice but putting it on the right would prevent it from obstructing the download titles. But to be honest I think it's something I can used to after a while.

**Comment by gitttt54** [comment]
Hello and sorry for the late reply.

> > old: 1 click to open the clipboard, curser was already in the textbox, so I could just paste the content and click "submit".
> > now its 2 clicks more to focus the clipboard and to close the 3 dot menu again
> 
> So it seems that adding auto focusing on the clipboard text box would solve this issue: first click on the 3 dots, fill the content of the clipboard, then second click to close the menu.

I will love to try this if it is available.

 
> > which also hides too much of my screen
> 
> You can collapse the Settings section to make the menu smaller.

As far as I remembr, collapsing would close the clipboard box and so I can not type anything.


> > I can not read the content of my tabs while typing or pasting to the clipboard.
> 
> Because of the new position of the menu ? The old Clipboard box was also taking a similar amount of space.

Yes, because of the new position. It now expands over the downloads-tab and hides most (of course, the important text in the middle) of the lines.
The old box was not hiding too much of important text, because the box was on the top of the window and was only hiding jd2 buttons, not the download-items.


>Finally, having the choice of the location of the 3 dots (left or right side) might be something possible. I will look at this.
That would be great. Let the user chose, where to put dat 3 dots. left/right corner of the screen or top/bottom. The position of the 3 dots is movable, yes, but as I wrote, having the dock left too will automaticly open the dock if I move the mouse 2 pixels to far and thus will take 2 seconds while I can not open the clibboard box becasue the dock is hiding after 2 seconds and reveals the 3 dots.

Funny, how a small change can make virtual life much harder ;-D

**Comment by pchristod** [comment]
@jlesage I quite like this new menu, much more convenient imo and more pleasing to look at. Out of interest, what practical use do these two sliders (Quality & Compression) serve. I can't see any difference no matter if both are on the lowest or highest setting. I would expect them to control the visual Quality of the App I guess.

**Comment by oystermon** [comment]
just did a quick test and works well.. thanks for the enhancements 👍

**Comment by jlesage** [comment]
> Out of interest, what practical use do these two sliders (Quality & Compression) serve. I can't see any difference no matter if both are on the lowest or highest setting. I would expect them to control the visual Quality of the App I guess.

@pchristod, sorry I forgot to answer this.  For an application like JDownloader, these settings won't have a big impact because the content of the UI is not changing a lot.  But if you try for example the Firefox Docker container and start to play a Youtube video with it, you should definitely see a difference when adjusting the settings.

**Comment by pchristod** [comment]
Thanks, appreciate the answer and explanation!

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.

**Comment by gitttt54** [comment]
I have never updated and use an [old](https://github.com/jlesage/docker-jdownloader-2/issues/116#issuecomment-1320719955) docker container ever since. 
that will hopefully work forever :-)

thank you!
