### ISSUE TITLE
Ctrl+Click and Shift+Click to select multiple items no longer working after UI update.

### ISSUE THREAD

**Issue by reecespieces** [jlesage/docker-jdownloader-2#122]
Before the UI update that changed the clipboard (referenced in #116), I was able to Ctrl+Click or Shift+Click to select multiple items, but these actions are not working anymore. This is a pretty big deal for me. Not being able to do those things makes some tasks ridiculously slower than they used to be.

**Comment by jlesage** [comment]
This is working for me.  Can you provide an example where this is not working ?  Which browser are you using ?   Do you have the same behaviour with different browsers ?

**Comment by jlesage** [comment]
Great, glad to see that you found the issue.
