### ISSUE TITLE
Restart loop after updating to Version 22.12.1

### ISSUE THREAD

**Issue by krownee** [jlesage/docker-jdownloader-2#127]
The latest version of docker-jdownloader-2 is stuck in a restart loop for me. 
Version 22.11.1 was working great.

**Comment by jlesage** [comment]
Can you provide the output of:
- `docker logs <container name>`
- `docker inspect <container name>`

**Comment by krownee** [comment]
Thanks for the quick reply, I managed to fix it by redeploying and assigning a network. There were no network assigned anymore somehow.
