### ISSUE TITLE
Having a hard time finding where my files were downloaded to

### ISSUE THREAD

**Issue by bryanmanio** [jlesage/docker-jdownloader-2#139]
I'm very new to this, so apolgies in advance.

I have jdownloader up and running, and had set the output folder to what I thought was the /output folder in docker/jdownloader2/output

I grabbed a bunch of files, but that folder is completely empty.

https://imgur.com/a/HIw7ait

This is what my folder was set to in downloader, is this on the root directory?

https://imgur.com/a/aSZmKmZ

I thought it was, but when I navigated there through ssh, that folder is empty.

https://imgur.com/a/UU4e4QN

Here is a screenshot showing that the files have been downloaded in downloader

https://imgur.com/a/3zFyBom

Any ideas? I just want to move these files to a shared folder in my home directory.

**Comment by jlesage** [comment]
In the container's settings, did you add this folder mapping under `Volume` tab?

**Comment by bryanmanio** [comment]
Ugh, such a simple stupid mistake. Everything is good to go, thanks!
