### ISSUE TITLE
problems with permissions

### ISSUE THREAD

**Issue by neuroryuu** [jlesage/docker-jdownloader-2#141]
I have problems with the permissions of the downloaded files although in umask I have them in 000 also try with 0000 and always write the folders or files with 770 and are not accessible from my windows I have q change permissions to folders manually from my unraid panel

**Comment by neuroryuu** [comment]
Edit: solved

This was found to be due to the remnants of being in Active Directory, but instead of being a permissions issue, it was an extended ACL issue. Using the command "setfacl -Rb /mnt/user/" resets the ACL on all user shares, then reruns the docker safe permissions tool and voilà, dockers can assign permissions as expected

**Comment by jlesage** [comment]
Great that you found the problem!

Do you know why ACLs existed on /mnt/user ?
