### ISSUE TITLE
Add Docker secrets support for MyJDownloader credentials

### ISSUE THREAD

**Issue by RealGreenDragon** [jlesage/docker-jdownloader-2#143]
Hi,

as "MYJDOWNLOADER_*" environment variables contain reserved data, can be good to support [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/) for them.

Thanks in advance

**Comment by jlesage** [comment]
Yes you should be able to use secrets by prepending `CONT_ENV_` to its name.  For example, you can create a secret named `CONT_ENV_MYJDOWNLOADER_PASSWORD`, with its content being the password.

**Comment by RealGreenDragon** [comment]
It works, I missed [Docker Secrets](https://github.com/jlesage/docker-baseimage-gui#docker-secrets) section on base image documentation.

Thank you very much.
