### ISSUE TITLE
Connection to MyJdownloader aborts

### ISSUE THREAD

**Issue by Nevarro** [jlesage/docker-jdownloader-2#144]
I'd like to use the MyJdownloader service. However, my docker instance appears briefly and then the connection aborts. I'm not sure whether this is a problem on my end or if it's a known problem with this container. I used the script-start version on my Synology NAS before and there had never been a problem before. 

Edit: Sorry, read the documentation on MYJD too late.

**Comment by charl3y15** [comment]
What documentation?
