### ISSUE TITLE
Is it possible to set the logout timeout longer?

### ISSUE THREAD

**Issue by Ninelpienel** [jlesage/docker-jdownloader-2#147]
Hey, I noticed that the web connection logs me out after just a few minutes. Is it possible to extend the time?

**Comment by jlesage** [comment]
Are you using a direct connection to the IP/port ?  Or through a reverse proxy ?

**Comment by Ninelpienel** [comment]
I use a reverse proxy.

**Comment by panosru** [comment]
You can use `proxy_read_timeout 120m;` setting if you are using Nginx Proxy Manager in the Advanced tab of your proxy host, like so:

![image](https://github.com/jlesage/docker-jdownloader-2/assets/400362/3527728e-de3b-4c6c-85f1-00feeec50eca)

`120m` stands for 120 minutes, you can change the timeout according to your needs.

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
