### ISSUE TITLE
Problem to use apache2 as reverse proxy

### ISSUE THREAD

**Issue by boospy** [jlesage/docker-jdownloader-2#149]
Hello all, 

i use Univention UCS (Debian) as applicationserver with docker CT's. On that apache2 is the default for all docker containers. So for example vaultwarden and the second one jdownloader.

```
ProxyPass /vaultwarden http://127.0.0.1:40050/ retry=0
ProxyPassReverse /vaultwarden http://127.0.0.1:40050/

ProxyPass / http://127.0.0.1:5800/ retry=0
ProxyPassReverse /jdownloader http://127.0.0.1:5800/
```
But if i open the url "https://app.tux.lan/jdownloader" i get the error that the site is not available. What i'am doing wrong? Here is my dockcommand:

`docker run -d -e UMASK=000 -e DARK_MODE=1 -e MYJDOWNLOADER_DEVICE_NAME=Appserver -e KEEP_APP_RUNNING=1 -e LANG=de_DE.UTF-8  -e TZ=Europe/Vienna --name=jdownloader-2 -p 5800:5800 -v /docker/appdata/jdownloader-2:/config:rw -v /mnt/Downloads/JDOWNLOADER:/output:rw jlesage/jdownloader-2`

But i can open "http://app.tux.lan:5800"

Very thanks :)

**Comment by jlesage** [comment]
> i get the error that the site is not available

What is the error exactly ?  Nothing is loaded ?

**Comment by boospy** [comment]
I have now install an fresh Ubuntu 22.04 with up2date docker from docker website and i use now nginx as reverse proxy. Now it work fine :+1:
