### ISSUE TITLE
v1.5.0 crash when adding a link

### ISSUE THREAD

**Issue by gerrit507** [jlesage/docker-jdownloader-2#15]
I recently updated to v1.5.0. Everytime I add a link the docker container exits. I only see the scanning pop-up followed by the captcha(open circle) and then the screen goes black. This issue doesn't exist with v1.4.3.

Just say if you need logs or anything...

**Comment by jlesage** [comment]
Which captcha methods are you using?  Do you know which one is causing the crash?  Is the link you are adding can be shared so I can try to reproduce?

**Comment by gerrit507** [comment]
It's an open circle captcha by filecrypt.cc.

Yes the links are public but I guess I can not post them here, if you know what I mean :sweat_smile:

**Comment by jlesage** [comment]
I was able to reproduce by creating and encrypted link with filecrypt.cc:
https://filecrypt.cc/Container/E5C1F51ECC.html

Just add this link to JDownloader on a freshly create container.

**Comment by gerrit507** [comment]
Thanks, it's working again :smile:

Amazing project with great support 👍
