### ISSUE TITLE
MyjDownloader loses connection

### ISSUE THREAD

**Issue by Nevarro** [jlesage/docker-jdownloader-2#153]
The connection to MjD is very unstable. Sometimes, it works for a longer period, then there is no connection possible only to be possible again later in the day. 

In configured the service as provided in the documentation. Does anyone else have this problem? Is there any solution?

**Comment by jlesage** [comment]
Do you have any error to share when the connection is not working ?

**Comment by Nevarro** [comment]
> Do you have any error to share when the connection is not working ?

Not really. Accessing via VNC shows that myjDownloader would still be working. 

I'd be happy to provide a log if you were able to tell me how to send it to you.

**Comment by jlesage** [comment]
> Accessing via VNC shows that myjDownloader would still be working.

So JDownloader shows that it is connected ?  Then how do you see that the connection is not stable ?

**Comment by Nevarro** [comment]
> So JDownloader shows that it is connected ?  Then how do you see that the connection is not stable ?

I can access via VNC at all times. However, the MjD-App on iOS loses the connection and my jD-Instance on the MjD-Website isn't shown anymore. 

If I deactivate and immediately activate the MjD-Service again, it's shown as online again. Sometimes for a longer period of time, sometimes the connection is lost again rather quickly.

**Comment by Nevarro** [comment]
@jlesage Any idea on how to fix this? jDownloader itself doesn't offer Docker-Support. There is nothing show in the Docker log, when the connection disappears. I have connected via myjDownloader this morning via browser. I can add things and delete finished downloads and then, after around a minute, the connection is lost. It reappears after 2-3 minutes and when I interact via the web gui, the connection is lost again. VNC connections are not affected.

**Comment by jlesage** [comment]
I don't think it's a docker related issue, but more a network related issue.  Do you have any firewall or network security services that might affect the connection ?

When my.jdownloader.org shows your instance as disconnected, what the JDownloader UI (VNC) is showing under the My.JDownloader tab ?

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
