### ISSUE TITLE
sign in to myjdownloader after each restart

### ISSUE THREAD

**Issue by droopified** [jlesage/docker-jdownloader-2#155]
I really love how I'm able to have jdownloader on my unRAID via docker and me able to send downloads from my desktop to unRAID via the extension. The thing that is extremely annoying is that my login isn't saved. Each time the docker is restarted, I have to enter the email, password, and device again which is really annoying to the point where I say screw it and keep all a list of downloads till I can bulk download. I spend way more time entering my login then any other time interacting with jdownloader. My password is randomly generated so I have to bring that up first. Please help!

**Comment by jlesage** [comment]
I don't have this issue on my side.  Is it the only setting that is not kept after a restart of the container ?

**Comment by droopified** [comment]
Yeah it's the only thing that doesn't save. Never has. Unsure why then

**Comment by droopified** [comment]
should i reinstall it? i would hate to the history as its been ignoring duplicates. (used for game archiving)

**Comment by jlesage** [comment]
Do you see the same issue if, in JDownloader, you do File->Restart ?
Also, anything special with the container's settings, or you use the default ones ?

**Comment by electblake** [comment]
I use the environment variables `MYJDOWNLOADER_EMAIL` and password etc to auto-configure my.jdownloader.org login. Makes my portainer setup much more durable and hands-free.

They are described in docs https://github.com/jlesage/docker-jdownloader-2#environment-variables

**Comment by jlesage** [comment]
This is a good point.  @droopified, did you set your credentials in the container's settings?  The unRAID template has fields for those.

**Comment by droopified** [comment]
that variable did it. for some reason it wasnt in my template on unraid

**Comment by jlesage** [comment]
Using the variables is not required, but great if they fix your issue.
