### ISSUE TITLE
archiv extractor

### ISSUE THREAD

**Issue by Codfired** [jlesage/docker-jdownloader-2#157]
### Current Behavior

Hello, unfortunately i cannot erase the extractet archiv. the archiv yourself can i erease, pass the permissions is correct over the compose file.

### Steps To Reproduce

erease the folder with extractet files under defined/expected permission

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

over compose file

### Container log

```text
not log/error in myjdownloader
```

**Comment by jlesage** [comment]
Are you talking about the delete functionality of JDownloader (right-click -> Delete)?  This action only deletes the downloaded files, not the extracted ones.

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
