### ISSUE TITLE
Not enough space

### ISSUE THREAD

**Issue by Sledgehamma** [jlesage/docker-jdownloader-2#16]
First of all thanks for all your Dockers! I really appreciate it.
I'm running your Makemkv and mkvtoolnix Docker on my Qnap 453A without any issues. I installed this Docker the exact same way, but when I started it and go to its webpage it says that there is not enough space:
![screenshot 10](https://user-images.githubusercontent.com/19309778/46575549-64ac1f00-c9b7-11e8-9a78-de419d660275.png)
![screenshot 12](https://user-images.githubusercontent.com/19309778/46575550-64ac1f00-c9b7-11e8-8a5e-0da182e9dddc.png)
Might be a Qnap specific issue?

**Comment by jlesage** [comment]
Do you really have enough space on the disk/folder mapped to `/config`?

**Comment by Sledgehamma** [comment]
How can I check that? The NAS has just over one TB of free space.
As the Dockers are installed on the volume I though that it has the same space restriction as any other folder or share on my NAS.

**Comment by jlesage** [comment]
What the following command shows?
```
docker exec [container name] df -h
```

**Comment by Sledgehamma** [comment]
![unbenannt](https://user-images.githubusercontent.com/19309778/46699747-0b442a00-cc1b-11e8-9d19-7b053d677a7c.JPG)

**Comment by jlesage** [comment]
Did you try to use paths under `/share/CACHEDEV1_DATA/`?  I think on QNAP this is the way to go.

**Comment by Sledgehamma** [comment]
Yeah that seems to be the right way. However, I tried a little different root and followed the linuxserver tutorial on how to set up Docker:
https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/

Everything works now. Thanks for your help and for providing your Dockers! Much appreciated.

**Comment by jlesage** [comment]
Great, glad to know that it's now working for you!
