### ISSUE TITLE
[Bug] Issue with myjdownloader when password begins with "#".

### ISSUE THREAD

**Issue by emailkanji** [jlesage/docker-jdownloader-2#169]
### Current Behavior

Docker instance does not connect to myjdownloader when password starts with #. Did not test if # character in password elsewhere causes issue.

### Expected Behavior

Myjdownloader should work normally.

### Steps To Reproduce

Use myjdownloader login password that begins with # character.

### Environment

- OS: Debian
- OS version: 12 (bookworm)
- CPU: x86-64
- Docker version: 24.0.5
- Device model: Dell Latitude 3380
- Browser/OS: n/a

### Container creation

version: "3"
services:
   jdownloader:
    image: jaymoulin/jdownloader:latest
    container_name: jdownloader
    restart: unless-stopped
    volumes:
        - "./cfg:/opt/JDownloader/app/cfg:rw"
        - "./output:/opt/JDownloader/Downloads:rw"
        - "./logs:/opt/JDownloader/app/logs:rw" #optional
        - "/etc/localtime:/etc/localtime:ro" #optional
    environment:
            MYJD_USER: email@domain.com #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_PASSWORD: '#**********' #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
            MYJD_DEVICE_NAME: taichou #optional
            DARK_MODE: 1
            JDOWNLOADER_HEADLESS: 1
            KEEP_APP_RUNNING: 1
            WEB_LISTENING_PORT: 5800
    ports:
        - "3129:3129"
        - "9666:9666"
        - "5800:5800"

### Container log

```text
Deleted logs from before solution to bug was found. Sorry.
```

**Comment by jlesage** [comment]
It seems to work fine on my side.  Can you verify if the password is correctly set in `/config/cfg/org.jdownloader.api.myjdownloader.MyJDownloaderSettings.json` (inside the container) ?

Also, according to the provided config, you didn't map the `/config` folder.

**Comment by emailkanji** [comment]
I did check that the password was set correctly in docker instance. I found it while trying to diagnose my issue and the password and some other stuff were correctly being imported from the docker compose file.

The above config is working for me now after I changed the password. Maybe it was something other than beginning with a #.

**Comment by emailkanji** [comment]
I did check that the password was set correctly in docker instance. I found it while trying to diagnose my issue and the password and some other stuff were correctly being imported from the docker compose file.

The above config is working for me now after I changed the password. Maybe it was something other than beginning with a #.

Didn't mean to close it.

**Comment by jlesage** [comment]
Ok, so everything is working fine for you now ?
