### ISSUE TITLE
[Bug] CJK-font installation failed

### ISSUE THREAD

**Issue by bertqw** [jlesage/docker-jdownloader-2#175]
### Current Behavior

Installed cjk-font with container environment variable "ENABLE_CJK_FONT=1" but it failed.
If i disable it using "ENABLE_CJK_FONT=0", everything is working well. 

### Environment

- OS: Qnap
- OS version:
- CPU:
- Docker version:
- Device model: qnap
- Browser/OS:

### Container creation

version: '3'
services:
  jdownloader-2:
    image: jlesage/jdownloader-2
    environment:
      - ENABLE_CJK_FONT=1
    ports:
      - "5800:5800"
    volumes:
      - "/.../jdownloader-2:/config:rw"
      - "/.../JDownloads:/output:rw"
      
    restart: unless-stopped

### Container log

```text
[cont-init   ] 10-cjk-font.sh: executing...
[cont-init   ] 10-cjk-font.sh: installing CJK font...
[cont-init   ] 10-cjk-font.sh: fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
[cont-init   ] 10-cjk-font.sh: fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
[cont-init   ] 10-cjk-font.sh: fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
[cont-init   ] 10-cjk-font.sh: ERROR: unable to select packages:
[cont-init   ] 10-cjk-font.sh:   font-wqy-zenhei (no such package):
[cont-init   ] 10-cjk-font.sh:     required by: world[font-wqy-zenhei]
[cont-init   ] 10-cjk-font.sh: terminated with error 1.
```

**Comment by jlesage** [comment]
Fixed with the latest version of the image.
