### ISSUE TITLE
[Feature request] Support chrome clipboard

### ISSUE THREAD

**Issue by webysther** [jlesage/docker-jdownloader-2#176]
### Idea

Some docker like linuxserver, kasm and others start enable support for clipboard when using the vnc over browser, any chance to support this for all images that need this feature like this?

**Comment by jlesage** [comment]
Clipboard is already supported, so I guess you mean something else/different ?

**Comment by webysther** [comment]
Yes, I mean, When you open the webapp others ask permission to capture the content of clipboard automatic without the need to past inside:

![image](https://github.com/jlesage/docker-jdownloader-2/assets/750007/98fe0e5a-6c9b-458b-8164-623fa749e1db)

![image](https://github.com/jlesage/docker-jdownloader-2/assets/750007/6bf48705-1afb-433f-9f3e-ab67bfff6d44)

This make a lot easier to past content inside the app.

**Comment by webysther** [comment]
As a workaround I start using vnc with guacamole that support this feature and I was able to past direct.
