### ISSUE TITLE
[Feature request] Allow to set permission of package folder

### ISSUE THREAD

**Issue by SimeonEhrig** [jlesage/docker-jdownloader-2#178]
### Idea

If JD2 creates an folder for a package in the download folder, the permission is `770`. It would be good if I the permission could be modified. 

In my case, the output folder is a samba folder. I run the image in a rootless podmain container. The user, who is running the container is not a samba user. Therefore the folder needs ether the permission `775` or needs to be owned by my samba share group. I think setting the permission is much more easy.

**Comment by jlesage** [comment]
You can use the `UMASK` environment variable to change the permissions of files/folders created by the container.  See https://github.com/jlesage/docker-jdownloader-2#environment-variables for more details.

**Comment by SimeonEhrig** [comment]
@jlesage Thanks for the fast answer and sorry for the long reply. 

I played around with the `UMASK` and it solves my problem. But I'm still a little bit confused. I set the `UMASK` variable to `0000` which means folders created via download packages or archive extraction have the permission `drwxrwxrwx`. But the files (direct downloaded or extracted from archive) have still permission `-rw-rw-rw-`. Before I used the `UMASK=003` and the folders had permission `drwxrwxr--` and the files had permission `-rw-rw-rw-`.

Is this behavior correct? The [documentation](https://github.com/jlesage/docker-jdownloader-2#environment-variables) is talking about files.

**Comment by jlesage** [comment]
With a umask of `0003`, created directories should have `drwxrwxr--`, but created files should have `-rw-rw-r--`, not `-rw-rw-rw-` as you mentioned.

`umask` applies to created files and folders.  I will update the documentation to clarify this.

**Comment by SimeonEhrig** [comment]
Update: I need also to set the variable 

> With a umask of `0003`, created directories should have `drwxrwxr--`, but created files should have `-rw-rw-r--`, not `-rw-rw-rw-` as you mentioned.
> 
> `umask` applies to created files and folders. I will update the documentation to clarify this.

Your are right. Submask `003` creates file permission `-rw-rw-r--` and `000` creates file permission `-rw-rw-rw-`. It was my mistake.

**Comment by SimeonEhrig** [comment]
Yes. I was only confused that folders are executable and files not. That makes sense, because folders needs to be executable that you can use `cd`. But for the first moment, it was confusing. I think, if you update the documentation the problem should be also solved for upcoming new user :-)
