### ISSUE TITLE
on Qnap ts-251 cannot open the docker

### ISSUE THREAD

**Issue by blibli1** [jlesage/docker-jdownloader-2#183]
### Current Behavior

hi,
when I run the container I cannot see anymore the web link to start jdownloader.
any help would be really appreciated .
thanks
luca

### Environment

- OS:
- OS version:
- CPU:
- Docker version:
- Device model:
- Browser/OS:

### Container creation

from explore tab on my nas

### Container log

```text
│ Application:           JDownloader 2                                 │
    │ Application Version:   n/a                                           │
    │ Docker Image Version:  23.11.2                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] service 'logmonitor' is disabled.
[supervisor  ] loading service 'logrotate'...
[supervisor  ] all services loaded.
[supervisor  ] starting services...
[supervisor  ] starting service 'xvnc'...
[xvnc        ] Xvnc TigerVNC 1.13.1 - built Nov 17 2023 22:53:44
[xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc        ] Underlying X server release 12014000
[xvnc        ] Sun Nov 26 16:47:38 2023
[xvnc        ]  vncext:      VNC extension running!
[xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc        ]  vncext:      created VNC server for screen 0
[supervisor  ] starting service 'nginx'...
[nginx       ] Listening for HTTP connections on port 5800.
[supervisor  ] starting service 'openbox'...
[supervisor  ] starting service 'app'...
[supervisor  ] all services started.
[xvnc        ] Sun Nov 26 16:53:52 2023
[xvnc        ]  Connections: accepted: 192.168.1.32::54717
[xvnc        ]  VNCSConnST:  closing 192.168.1.32::54717: reading version failed: not an RFB
[xvnc        ]               client?
[xvnc        ]  EncodeManager: Framebuffer updates: 0
[xvnc        ]  EncodeManager:   Total: 0 rects, 0 pixels
[xvnc        ]  EncodeManager:          0 B (1:-nan ratio)
[xvnc        ]  Connections: closed: 192.168.1.32::54717
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ]  Connections: accepted: 192.168.1.32::54718
[xvnc        ]  VNCSConnST:  closing 192.168.1.32::54718: reading version failed: not an RFB
[xvnc        ]               client?
[xvnc        ]  EncodeManager: Framebuffer updates: 0
[xvnc        ]  EncodeManager:   Total: 0 rects, 0 pixels
[xvnc        ]  EncodeManager:          0 B (1:-nan ratio)
[xvnc        ]  Connections: closed: 192.168.1.32::54718
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ]  Connections: accepted: 192.168.1.32::54719
[xvnc        ]  VNCSConnST:  closing 192.168.1.32::54719: reading version failed: not an RFB
[xvnc        ]               client?
[xvnc        ]  EncodeManager: Framebuffer updates: 0
[xvnc        ]  EncodeManager:   Total: 0 rects, 0 pixels
[xvnc        ]  EncodeManager:          0 B (1:-nan ratio)
[xvnc        ]  Connections: closed: 192.168.1.32::54719
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ] Sun Nov 26 16:54:23 2023
[xvnc        ]  Connections: accepted: 192.168.1.32::54752
[xvnc        ]  VNCSConnST:  closing 192.168.1.32::54752: reading version failed: not an RFB
[xvnc        ]               client?
[xvnc        ]  EncodeManager: Framebuffer updates: 0
[xvnc        ]  EncodeManager:   Total: 0 rects, 0 pixels
[xvnc        ]  EncodeManager:          0 B (1:-nan ratio)
[xvnc        ]  Connections: closed: 192.168.1.32::54752
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ]  Connections: accepted: 192.168.1.32::54753
[xvnc        ]  VNCSConnST:  closing 192.168.1.32::54753: reading version failed: not an RFB
[xvnc        ]               client?
[xvnc        ]  EncodeManager: Framebuffer updates: 0
[xvnc        ]  EncodeManager:   Total: 0 rects, 0 pixels
[xvnc        ]  EncodeManager:          0 B (1:-nan ratio)
[xvnc        ]  Connections: closed: 192.168.1.32::54753
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc        ]  Connections: blacklisted: 192.168.1.32
[supervisor  ] SIGTERM received, shutting down...
[supervisor  ] stopping service 'app'...
[supervisor  ] stopping service 'openbox'...
[supervisor  ] service 'openbox' exited (with status 0).
[supervisor  ] stopping service 'nginx'...
[supervisor  ] service 'nginx' exited (with status 0).
[supervisor  ] service 'app' exited (with status 127).
[supervisor  ] stopping service 'xvnc'...
[xvnc        ] Sun Nov 26 16:56:16 2023
[xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor  ] service 'xvnc' exited (with status 0).
[finish      ] executing container finish scripts...
[finish      ] all container finish scripts executed.
```

### Anything else?

I don't know

**Comment by jlesage** [comment]
Looks like an QNAP related issue ?

Note that the container can always be accessed via the URL `http://XX.XX.XX.XX:YYYY`, where `XX.XX.XX.XX` is the IP address of your NAS and `YYYY` is the port you mapped to 5800.

**Comment by blibli1** [comment]
Hi,
I received an error message:
Safari cannot open the page because the address is not valid?
What can I do?

Thanks
Luca
Il 27 nov 2023, 14:15 +0100, jlesage/docker-jdownloader-2 ***@***.***>, ha scritto:
>
> 5800

**Comment by blibli1** [comment]
can I send the log or something else to understand what is the problem?
thanks

**Comment by jlesage** [comment]
- Make sure the container is running (in the logs you provided, it has been stopped).
- Provide the output of `docker inspect <container name>`.
- Provide the URL you used to connect to the container.

**Comment by blibli1** [comment]
I have tried also with the container running.
this is the docker inspect:
{
AppArmorProfile:"docker-default"
Args:[]
Config:{...}
Created:"2023-11-26T16:47:32.85098696Z"
Driver:"overlay2"
GraphDriver:{...}
HostConfig:{...}
HostnamePath:"/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/254ac4fe6451d30e8702d854dede71f45cc4c81d692a7b6d0d8860b590de1f78/hostname"
HostsPath:"/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/254ac4fe6451d30e8702d854dede71f45cc4c81d692a7b6d0d8860b590de1f78/hosts"
Id:"254ac4fe6451d30e8702d854dede71f45cc4c81d692a7b6d0d8860b590de1f78"
Image:"sha256:d544df040e95e5f0c4af3a962d9c15d0b2a9499fe29fb41a8370e71b45568bc3"
LogPath:"/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/254ac4fe6451d30e8702d854dede71f45cc4c81d692a7b6d0d8860b590de1f78/254ac4fe6451d30e8702d854dede71f45cc4c81d692a7b6d0d8860b590de1f78-json.log"
MountLabel:""
Mounts:[...]
Name:"/jdownloader-2-1"
NetworkSettings:{...}
Path:"/init"
Platform:"linux"
ProcessLabel:""
ResolvConfPath:"/share/CACHEDEV1_DATA/Container/container-station-data/lib/docker/containers/254ac4fe6451d30e8702d854dede71f45cc4c81d692a7b6d0d8860b590de1f78/resolv.conf"
RestartCount:0
State:{...}
}

the url is http://192.168.1.217:5800 or 5900.

**Comment by jlesage** [comment]
The output of `docker inspect` is incomplet ?

**Comment by blibli1** [comment]
please help me!!!

**Comment by blibli1** [comment]
but if the output inspector is not completed is there a way to reinstall in the proper way?
How Can I mapped the port?
I'm really sorry to bother you but I'm a beginner.
can you guide me to fix the container?
thanks for your time

**Comment by jlesage** [comment]
I don't have a QNAP so it's hard to give the exact steps.  But in Container Station, in advanced settings of the container, you should have a "Network" tab where you can define the mapping.

**Comment by blibli1** [comment]
<img width="336" alt="Screenshot 2023-11-29 alle 18 04 19" src="https://github.com/jlesage/docker-jdownloader-2/assets/152093518/8ec6d8db-e8e3-43c8-85e8-d23ebc79b2f2">
<img width="336" alt="Screenshot 2023-11-29 alle 18 04 52" src="https://github.com/jlesage/docker-jdownloader-2/assets/152093518/0a2aeee8-cabb-4dfc-bbd4-14ec1fb12362">
<img width="1041" alt="Screenshot 2023-11-29 alle 18 10 30" src="https://github.com/jlesage/docker-jdownloader-2/assets/152093518/555f9b66-8b1b-4009-8eba-f181ae4e696e">
thi
<img width="1041" alt="Screenshot 2023-11-29 alle 18 10 37" src="https://github.com/jlesage/docker-jdownloader-2/assets/152093518/ade3ebe9-aaac-432d-8865-a3f50a059a18">

**Comment by jlesage** [comment]
What do you have when your click the **+2** beside the "Port forwarding" label ?  This will probably show you what port is forwarded to `5800`.
<img width="336" alt="286685707-8ec6d8db-e8e3-43c8-85e8-d23ebc79b2f2" src="https://github.com/jlesage/docker-jdownloader-2/assets/1791123/5536d0b3-0c86-47d7-8ba0-7c4d2618e7b7">

**Comment by blibli1** [comment]
<img width="543" alt="Screenshot 2023-11-29 alle 19 04 53" src="https://github.com/jlesage/docker-jdownloader-2/assets/152093518/f4c47e49-bdf7-4c96-bf36-7b1c54cb51df">

**Comment by jlesage** [comment]
Ok, so port 5800 to mapped to 32801.  This means that you can access the container via http://192.168.1.217:32801.

**Comment by blibli1** [comment]
it works!!!!
thank you soooooo much!!!

**Comment by jlesage** [comment]
No problem!

**Comment by blibli1** [comment]
Hi,
do you know how to change the output of downloader and put the downloads folder on the Qnap?
I know how to change but I cannot find the structure of my Qnap.

**Comment by jlesage** [comment]
Normally you have to map a folder on the QNAP to `/output` inside the container.

This seems to be done under Advanced settings -> Storage: you should have an option "Bind Mount Host Path".

This might help: https://www.qnap.com/en/how-to/tutorial/article/how-to-use-container-station-3

**Comment by blibli1** [comment]
thank you so much!!! again!!!
