### ISSUE TITLE
 help to install

### ISSUE THREAD

**Issue by zatuz** [jlesage/docker-jdownloader-2#21]
2 things
1.- I'm bad for English
2.- Thank you very much for your great effort.
I just installed filebot
in the port: 5800
Aora I also want to install jdownloader2
but the tutorial mentions that you use port 5800: 5800
Can I change port?

**Comment by jlesage** [comment]
Yes you can change the host-side port.  The README just give a configuration example.  So instead of using `-p 5800:5800` you can use something like `-p 5801:5800`.
