### ISSUE TITLE
[Bug] No connection to the Internet

### ISSUE THREAD

**Issue by krzychu82** [jlesage/docker-jdownloader-2#219]
### Current Behavior

No connection to the internet. 
"JDownloader cannot connect to update.jdownloader.org! Please check the connection settings."

### Expected Behavior

Connection to the internet after installation.

### Steps To Reproduce

Run after installation

### Environment

- OS: DMS
- OS version: 7.2.1 -69057 Update 5
- CPU: Intel Celeron J4025
- Docker version: 20.10.23-1437
- Device model: DS220+
- Browser/OS: Chrome

### Container creation

docker run -d --name=jdownloader2 \
-p 3129:3129 \
-p 5800:5800 \
-p 5900:5900 \
-e USER_ID=1029 \
-e GROUP_ID=100 \
-e TZ=Europe/Bucharest \
-e DARK_MODE=1 \
-v /volume1/docker/jdownloader2/config:/config \
-v /volume1/docker/jdownloader2/output:/output \
--restart always \
jlesage/jdownloader-2

### Container log

```text
jdownloader2
date,stream,content
2024/08/16 10:17:49,stdout,[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888

2024/08/16 10:17:49,stdout,[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888

2024/08/16 10:17:49,stdout,[xvnc        ]  SConnection: Client requests security type None(1)

2024/08/16 10:17:49,stdout,[xvnc        ]  SConnection: Client needs protocol version 3.8

2024/08/16 10:17:49,stdout,[xvnc        ]  Connections: accepted: /tmp/vnc.sock

2024/08/16 10:17:49,stdout,[xvnc        ] Fri Aug 16 11:17:49 2024

2024/08/16 00:32:07,stdout,[xvnc        ]  ComparingUpdateTracker: (1:13774.5 ratio)

2024/08/16 00:32:07,stdout,[xvnc        ]  ComparingUpdateTracker: 62.6837 Gpixels in / 4.55072 Mpixels out

2024/08/16 00:32:07,stdout,[xvnc        ]  Connections: closed: /tmp/vnc.sock

2024/08/16 00:32:07,stdout,[xvnc        ]  EncodeManager:          1.78718 MiB (1:24.1568 ratio)

2024/08/16 00:32:07,stdout,"[xvnc        ]  EncodeManager:   Total: 1.345 krects, 11.3134 Mpixels
```

**Comment by jlesage** [comment]
Are you sure the container has access to the internet ? Do you have the firewall enabled on your Synology ?

**Comment by krzychu82** [comment]
I am so embarrassed. How could I missed it. Thank you. The ticket can be closed.

**Comment by lmosqueraa** [comment]
I have the same problem. Did you find a solution?

**Comment by jlesage** [comment]
Did you confirm that deactivating the firewall fixes the problem ?

**Comment by jlesage** [comment]
I don't know... but we must first understand where the problem is coming from. It's not clear to me if the container can access the internet at all or if it's a specific resource that has a problem.

**Comment by lmosqueraa** [comment]
Sorry I had a dns problem. I realized this because I was having problems with other containers not resolving correctly.
