### ISSUE TITLE
Invalid Directory

### ISSUE THREAD

**Issue by vic1707** [jlesage/docker-jdownloader-2#24]
Hi, first huge thanks for this easy install package for JDownloader.
All is fine except that i can't download my files : error "invalid download directory", because i'm an absolute begginer with docker i've added the volume with the modify button of the container, i've added a path to download but as i said i get an error for invalid directory.
Can somebody help me?

![how i added the volume](https://user-images.githubusercontent.com/28602203/51411181-3a95fb80-1b67-11e9-99d0-b59038ee0a28.png)

**Comment by vic1707** [comment]
fix! just needed to set userID to 0 and same for group but no changes it's still to 1000.

**Comment by jlesage** [comment]
Ideally you should try to set a `USER_ID` and `GROUP_ID` that allow the container to access your download folders.  See https://github.com/jlesage/docker-jdownloader-2#usergroup-ids
Running the container as root will work, but it is not a best security practice...

**Comment by skorpion1298** [comment]
On my QNAP I´ve set it to 0 and 0 and now it works. This is the Admin ID and Admin Group.

**Comment by jlesage** [comment]
Maybe QNAP calls it differently, but user/group id `0`/`0` is root.

**Comment by deoese** [comment]
You need to access the terminal of the system. If you can't access it directly, try enabling SSH and connect remotely or locally via SSH.

Log in with your username and password, and then use the **id** command to get the uid (user ID) and gid (group ID) of the user.

If you need to check the uid and gid for a different user, use id <username>, replacing <username> with the desired username.

Once you have the correct USER_ID and GROUP_ID, update your container configuration accordingly and restart the container. It should work properly.

Alternatively, you can run the container as ROOT by setting both USER_ID and GROUP_ID to 0. However, for security reasons, it's better to use the specific IDs for the user you need.
