### ISSUE TITLE
Reverse Proxy Secure Connection VNC Password Problem

### ISSUE THREAD

**Issue by Oli1990** [jlesage/docker-jdownloader-2#25]
Hello,

i have an issue on my jdownloader 2 docker container on my Synology NAS.
I have set SECURE_CONNECTION Variable in the docker container to 1. Also I have configured VNC to use a password when i connect to the container via a web browser over port 5800 with the .vncpass_clear file in the /config dir.
And last but not least I have a reverse proxy on my NAS which makes a https domain external with SSL certificate internal to port 5800 on my NAS.

When I go the the website https://mynas:5800 all works fine and the popup for the VNC password is shown. But when I use the URL from the reverse proxy https://jdownloader.mydomain:443 I can connect to the website but the popup for the password is not shown and the website says server disconnected (code: 1006). 
Do I have to add some more lines to my reverse proxy setup or what did I do wrong?
Hope you can help me and thanks a lot.

Best regards

**Comment by gerrit507** [comment]
You have to disable SECURE_CONNECTION on the docker if you use a reverse proxy. Then the setup looks like this:
client <-- https --> reverse proxy <-- http --> container

I use this configuration across all my containers.

**Comment by Oli1990** [comment]
Hello,

thank you for your comment. Tested this setup right now. Is also not working. I think this has something to to with the port mapping in the reverse proxy. Which ports are you using in your described setup above? In my setup is client <-- https 443 -->> reverse proxy <--https 5800 --> container. or right now tested client <-- https 443 --> reverse proxy <-- http 5800 --> container.
Thank you.

**Comment by jlesage** [comment]
I tested the container behind a reverse proxy and it's working well with a VNC password.
How did you created the container (what is your docker command)?  You can also provide the output of `docker inspect <container name>`.

**Comment by Oli1990** [comment]
Hello,

i downloaded the container from the docker hub via the docker application on DSM operating system on a Synology NAS.
Is your container also working with SECURE_CONNECTION = 1?

**Comment by eeschiavo** [comment]
Hello, I have the exact same issue. Is there any fix available? Thanks

**Comment by jlesage** [comment]
I have found no issue so far.  How did you created the container and what is your proxy configuration?

**Comment by wzchua** [comment]
If you add the reverse proxy via DSM gui, you need to create the websocket header in the Custom Header. 
Go to the Custom Header tab. Click the down arrow next to Create, and click Web Socket. and save

**Comment by Oli1990** [comment]
Hello,Thank you for your answer. This is the solution for the problem.Thank you.Best regardsVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Wei Zheng <notifications@github.com> Datum: 17.03.19  09:48  (GMT+01:00) An: jlesage/docker-jdownloader-2 <docker-jdownloader-2@noreply.github.com> Cc: Oli1990 <olivergoetz1@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [jlesage/docker-jdownloader-2] Reverse Proxy Secure Connection VNC Password Problem (#25) If you add the reverse proxy via DSM gui, you need to create the websocket header in the Custom Header.
Go to the Custom Header tab. Click the down arrow next to Create, and click Web Socket. and save

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jlesage/docker-jdownloader-2","title":"jlesage/docker-jdownloader-2","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jlesage/docker-jdownloader-2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wzchua in #25: If you add the reverse proxy via DSM gui, you need to create the websocket header in the Custom Header. \r\nGo to the Custom Header tab. Click the down arrow next to Create, and click Web Socket. and save"}],"action":{"name":"View Issue","url":"https://github.com/jlesage/docker-jdownloader-2/issues/25#issuecomment-473637349"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jlesage/docker-jdownloader-2/issues/25#issuecomment-473637349",
"url": "https://github.com/jlesage/docker-jdownloader-2/issues/25#issuecomment-473637349",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Crykin** [comment]
I am also having this problem on DSM 7: server disconnected (code: 1006)

VNC works fine and SECURE_CONNECTION is set to 0

I have created the WebSocket header, reverse proxy settings are:
https://jd2.mydomain.com --> synology reverse proxy --> http://localhost:5800
