### ISSUE TITLE
Permission deny with docker image

### ISSUE THREAD

**Issue by lantura** [jlesage/docker-jdownloader-2#26]
Can anybody help with this issue? Thanks.
docker run -d \
> --name=jdownloader-2 \
> -p 5800:5800 \
> -v /docker/appdata/jdownloader-2:/config:rw \
> -v $HOME/Downloads/Jdown:/output:rw \
> jlesage/jdownloader-2
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.29/c                       ontainers/create?name=jdownloader-2: dial unix /var/run/docker.sock: connect: pe                       rmission denied.
See 'docker run --help'.

**Comment by jlesage** [comment]
Did you run the command as root?

**Comment by lantura** [comment]
Thanks, with root installation has been worked. 
Only this message has been displayed:
docker: Error response from daemon: Bind mount failed: '/docker/appdata/jdownloa                                                          der-2' does not exists.

The first download was saved to /output (acc. to GUI) but on both volumes the downloaded file could not be find. I thought with the -v option the download directory has been specified. And the options with right click on the downloaded file in JD GUI ("Open File" and "Open Download Directory") could not be choosed.
Or do I have to mount the download directory to /output within the docker GUI of my Synology?
Thanks in advance.

**Comment by lantura** [comment]
I have mounted the download directory via Docker GUI and the download has been worked.
Thanks for the support.
