### ISSUE TITLE
Downloading straight to a CIFS mounted share (Samba share) always crashes the GUI and fails the CRC check

### ISSUE THREAD

**Issue by recklessnl** [jlesage/docker-jdownloader-2#27]
Hi jlesage, was hoping you could help me with this - I have mounted a CIFS share via /etc/fstab that works fine normally. I can create directories and files from the VM I'm running it in without any issues.

I'm running this docker image in a VM dedicated to this, so I want to run docker as root. I have USER_ID=0 and GROUP_ID=0 as I'm the root account and I don't want any permission troubles within the VM. I can tell that it can write and that the files download because I see the .part files appearing on the samba share. 

However, two things happen:
1) I immediately lose control over the GUI, it freezes completely. I reload the page, same thing. The only way it stops freezing and lagging all over the place is when the download actually completes.
2) Once it completes, I always get the same error: "An error occured!" "[MD5] CRC failed!"
3) This does NOT happen when I download to a local mounted folder within the VM. I don't get a crashing and freezing GUI, nor the MD5 CRC fail on every single download (all checks pass without any issues).

Do you have any ideas what this could be?  Thanks in advance.

**Comment by jlesage** [comment]
Did you look at the log files under in the `logs` directory (under the folder you mapped to `/config`)?
Maybe there is something that could help.

**Comment by recklessnl** [comment]
This turned out to be a much more complicated issue with a NIC, so ultimately it had nothing to do with your docker image. It works perfectly fine! Closing this issue.
