### ISSUE TITLE
openbox permission error

### ISSUE THREAD

**Issue by Dikay900** [jlesage/docker-jdownloader-2#28]
I rebuilt the docker image and i am getting the following errors starting up a containter:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing... 
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing... 
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing... 
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing... 
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing... 
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing... 
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing... 
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing... 
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing... 
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing... 
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing... 
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing... 
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] jdownloader2.sh: executing... 
[cont-init.d] jdownloader2.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting nginx...
[services.d] starting xvfb...
[nginx] starting...
[xvfb] starting...
[services.d] starting certsmonitor...
[services.d] starting x11vnc...
[services.d] starting statusmonitor...
[x11vnc] starting...
[certsmonitor] disabling service: secure connection not enabled.
23/03/2019 08:18:55 passing arg to libvncserver: -rfbport
23/03/2019 08:18:55 passing arg to libvncserver: 5900
23/03/2019 08:18:55 passing arg to libvncserver: -rfbportv6
23/03/2019 08:18:55 passing arg to libvncserver: -1
23/03/2019 08:18:55 passing arg to libvncserver: -httpportv6
23/03/2019 08:18:55 passing arg to libvncserver: -1
23/03/2019 08:18:55 passing arg to libvncserver: -desktop
23/03/2019 08:18:55 passing arg to libvncserver: JDownloader 2
23/03/2019 08:18:55 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 733
[services.d] starting openbox...
[statusmonitor] no file to monitor: disabling service...
23/03/2019 08:18:55 Using X display :0
23/03/2019 08:18:55 rootwin: 0x43 reswin: 0x200001 dpy: 0x60acda00
23/03/2019 08:18:55 
23/03/2019 08:18:55 ------------------ USEFUL INFORMATION ------------------
[openbox] starting...
Error loading shared library libintl.so.8: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libXcursor.so.1: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libstartup-notification-1.so.0: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libobrender.so.32: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libobt.so.2: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libSM.so.6: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libICE.so.6: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libX11.so.6: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libXinerama.so.1: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libXrandr.so.2: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libXext.so.6: Permission denied (needed by /usr/bin/openbox)
Error loading shared library libglib-2.0.so.0: Permission denied (needed by /usr/bin/openbox)
Error relocating /usr/bin/openbox: g_free: symbol not found
Error relocating /usr/bin/openbox: xqueue_listen: symbol not found
Error relocating /usr/bin/openbox: obt_prop_get_array_text: symbol not found

Any way to get around this permission error? Container is stopping after throwing symbol not found errors afterward and exiting saying jdownloader does not run anymore.

**Comment by Dikay900** [comment]
well after starting everything as root and setting app user to root and gui uid to 0 it works. Still seems wrong to me but works for me. Can be closed if  you think this correct behaviour.

**Comment by jlesage** [comment]
So you are using your own image instead of the official one?  Do you have the same issue with the image from Docker hub?

**Comment by Dikay900** [comment]
yes i had the same issue with the official one, then used building myself since i wanted to fix this. Seemed to be a permission error at best.

**Comment by jlesage** [comment]
This seems to be an issue with your docker environment.  Which device/os are you using?

Try to run `docker exec <container name> ls /usr/lib/` to see the permission on files.

**Comment by Dikay900** [comment]
yeah could be related to my environment just retested again and it is working now out of the box with your image. thanks
