### ISSUE TITLE
Disable GUI

### ISSUE THREAD

**Issue by Somebody25** [jlesage/docker-jdownloader-2#32]
Is there a possibility to run the jDownloader without the GUI in Browser or the VNC Server? It would be great if it was possible to make the initial settings to myjDownloader and then disable the GUI access altogether. Then one wouldn't have to worry about the security of the GUI.

**Comment by jlesage** [comment]
This is something that will eventually be possible.

However, if you want to prevent access to the UI right now, you just need to *not* map port 5800 (assuming your are using the default `bridge` network mode).

**Comment by Somebody25** [comment]
Alright, that worked. I was just a little bit confused because the port is declared as mandatory and I was afraid that the server wouldn't work at all but it does. Thanks!
