### ISSUE TITLE
Scale up or stretch to fit larger browser window

### ISSUE THREAD

**Issue by tarchive** [jlesage/docker-jdownloader-2#33]
Hi,
i am coming from Aptalca's Jdownloader2 docker and have gotten quite used to the auto webgui up/down scaling. In yours i see an option to downscale which works perfectly but there is not one to upscale. How would you recommend accomplishing this with your docker image?

Just to clarify, i am not talking about changing the DISPLAYWIDTH/DISPALYHEIGHT variables.
I am asking this so when i set a 1080p resolution in the jdownloader docker and i open the webui on a 1080p monitor it will fit perfectly and on a 4k monitor it will upscale automatically. Eliminating the blanks space and the bottom and sides.

I have tried setting the docker resolution to fit the 4k monitor perfectly and with the downscale option enabled, it does shrink it for the 1080p monitor however the result is unusable because the text is so tiny.

The opposite of this would be ideal and is why i am asking for a upscale option. 

Thanks in advance for your help.

**Comment by jlesage** [comment]
Upscaling is currently not possible.  However, in the future, it could be possible to dynamically adjust the resolution of the app to match the size of the window browser.

**Comment by tarchive** [comment]
Yes, that would work too. I look forward to that dynamic resolution feature here if it becomes possible.

In the meantime i did some playing around with the html inside chrome dev menu and found increasing the width and height to 2560 and 1310 in the element below i could stretch the 1080p window to fit my 4k screen exactly as i was hoping to accomplish. There is a very small gap at bottom but it is needed to prevent chrome from displaying scrollbars.
```
<canvas id="rfbScreen" class="center-block" style="margin-top: 51px; width: 2560px; height: 1310px;" width="1920" height="1080" data:image="">
    Canvas not supported.
  </canvas>
```

The problem is now the jdownloader mouse it out of sync with the host mouse . Probably a different scaling factor somewhere, but I do not know enough to begin digging further and honestly not sure if it will lead to a feasible workaround.

**Comment by jlesage** [comment]
With the latest image, resolution is now automatically adjusted according to the browser's window size.
