### ISSUE TITLE
Captcha Dialog problem with MyJDownloader

### ISSUE THREAD

**Issue by Robert-Arctor** [jlesage/docker-jdownloader-2#34]
Hello,

I have a problem with the docker instance of JDownloader.
The Captchas are not displayed properly at MyJDwonloader anymore.
The captcha notification pops up for a split second, but even if i manage to click in the notification in that short time frame the captcha solving window does not open.

The captcha solving was working before, but i haven't used JDownloader for a month or two and now it stopped working. Unfortunately I don't know if it is due to a system update or an update of the docker image that I made in the meantime when i wasn't using JDownloader.

I can still access the MyJDownloader GUI besides the captcha dialog, so i can see 'Downloads', 'LinkGrabber' etc. and i can download files without captcha protection.

I'm using it on linux x86_64 Ubuntu 18.04.2 LTS, kernel: 4.15.0-52-generic, docker v18.09.6-build481bc77, docker-compose v1.23.2.

The Captcha dialog in MyJDownloader still works with my Windows laptop JD instance.

Here is a little selection of my output.log file:

> THREAD: 40
40|Log.L.log 6/21/19 2:39:18 PM - INFO [ org.appwork.storage.JsonKeyValueStorage(<init>) ] -> Prefer (merged) JSon Storage from File: /config/cfg/org.jdownloader.api.captcha.CaptchaMyJDownloaderRemoteSolverSettings.json
40|Log.L.log 6/21/19 2:39:18 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /captcha = interface org.jdownloader.api.captcha.CaptchaAPI
40|Log.L.log 6/21/19 2:39:18 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /captchaforward = interface org.jdownloader.captcha.api.CaptchaForwarderAPIInterface
40|Log.L.log 6/21/19 2:39:18 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /jd = interface org.jdownloader.api.jd.JDAPI
40|Log.L.log 6/21/19 2:39:18 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloads = interface org.jdownloader.api.downloads.DownloadsAPI
40|Log.L.log 6/21/19 2:39:19 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloadsV2 = interface org.jdownloader.api.downloads.v2.DownloadsAPIV2
40|Log.L.log 6/21/19 2:39:19 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /downloadcontroller = interface org.jdownloader.api.downloads.v2.DownloadWatchdogAPI
40|Log.L.log 6/21/19 2:39:19 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /config = interface org.jdownloader.api.config.AdvancedConfigManagerAPI
40|Log.L.log 6/21/19 2:39:19 PM - INFO [ org.appwork.loggingv3.LogV3(info) ] -> Try to register API namespace /toolbar = interface org.jdownloader.api.toolbar.JDownloaderToolBarAPI

Is this part of the log-file helpful? I don't really know what to look for in this file. Is it helpful to post the whole output.log or other log-files? If yes which?

Do you know what could be the problem here and how can i debug/fix it?

thank you very much for your help!

Best regards,

Bob

**Comment by jlesage** [comment]
Are you using the MyJDownloader browser plugin?

**Comment by Robert-Arctor** [comment]
Yes, I'm using the Browser Plugin. I tested it with Chrome and Firefox, both with Plugins installed on a Win 10 PC. I also tested the MyJDownloader Android App. I get the same results on all machines. Captchas of my Docker JD Host are not displayed, despite the fact that the captchas of the normal Windows JD instance work. Both are in the same network, so i think it doesn't seem to be a router firewall issue either.

Is there anything i can check/try to narrow the problem down?

Thanks!

**Comment by jlesage** [comment]
I would make sure that:
  - JD is up-to-date: Help->Find Updates
  - You are properly logged to My.JDownloader: Settings -> My.JDownloader
  - The My.JDownload captcha plugin is enabled: Settings -> Captchas

**Comment by jlesage** [comment]
Also, you could try to start the container with a clean appdata folder: Stop the container, rename the folder you mapped to `/config` and then start the container.

**Comment by Robert-Arctor** [comment]
Hello jlesage,

i tried everything that you recommended but it still doesn't work.
I deleted the /config folder and started the container fresh. The captchas are still not displayed at MyJDownloader. Do you have any more suggestions? Do you knows what else could be the reason?

Thanks for your help!

Rob

**Comment by Robert-Arctor** [comment]
Hi,

i just installed the current ubuntu 18.04 updates of this week and captcha solving does work again.
I don't know what has caused it in detail but it seems like it got fixed with the current updates.

Thank you for your help!

best regards,

Rob

**Comment by jlesage** [comment]
Great, glad to see that it's now working for you !
