### ISSUE TITLE
[CERT] doesn't start when using the eff certbot in default

### ISSUE THREAD

**Issue by SoulInfernoDE** [jlesage/docker-jdownloader-2#35]
As you can see when i start the container this happens:

> [cont-init.d] 00-take-config-ownership.sh: executing... 
> 
> chown: /config/certs/cert.pem: Read-only file system
> 
> chown: /config/certs/privkey.pem: Read-only file system
> 
> chown: /config/certs/chain.pem: Read-only file system
> 
> chown: /config/certs/fullchain.pem: Read-only file system
> 
> chown: /config/certs/README: Read-only file system
> 
> chown: /config/certs: Read-only file system
> 
> chown: /config/certs: Read-only file system
> 
> [cont-init.d] 00-take-config-ownership.sh: exited 0.
> 
> [cont-init.d] 00-xdg-runtime-dir.sh: executing... 
> 
> [cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
> 
> [cont-init.d] 10-certs.sh: executing... 
> 
> [cont-init.d] 10-certs.sh: Generating DH parameters (2048 bits), this is going to take a long time...
> 
> [cont-init.d] 10-certs.sh: exited 1.
> 
> [services.d] stopping services
> 
> [services.d] stopping s6-fdholderd...
> 
> [cont-finish.d] executing container finish scripts...
> 
> [cont-finish.d] done.
> 
> [s6-finish] syncing disks.
> 
> [s6-finish] sending all processes the TERM signal.
> 
> [s6-finish] sending all processes the KILL signal and exiting.

So i am using your container on a debian stretch machine with default generated LE certificates. (My operating system is named: LMDE3)

**The certbot puts the generated files secured and linked at this location:**
/etc/letsencrypt/live/< redacted > / *

It seems the container is searching for **web**-privkey.pem and **web**-fullchain.pem instead of the standard eff format.
The problem this generates is that the certificates created and renewed from the eff certbot are secured and linked automatically. Changing them would lead to not beeing able to renew the certificates without renaming anything.

[Here](https://portainer.readthedocs.io/en/stable/deployment.html) are some example details:
![grafik](https://user-images.githubusercontent.com/3682343/62479552-03f39b80-b7ae-11e9-9777-57541c34b598.png)

Similiar issue/description with the docker - portainer: -
#https://github.com/portainer/portainer/issues/2302

**README of certbot says this:**

> This directory contains your keys and certificates.
> 
> `privkey.pem`  : the private key for your certificate.
> `fullchain.pem`: the certificate file used in most server software.
> `chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
> `cert.pem`     : will break many server configurations, and should not be used
>                  without reading further documentation (see link below).
> 
> WARNING: DO NOT MOVE OR RENAME THESE FILES!
>          Certbot expects these files to remain in this location in order
>          to function properly!
> 
> We recommend not moving these files. For more information, see the Certbot
> User Guide at https://certbot.eff.org/docs/using.html#where-are-my-certificates.

**Comment by jlesage** [comment]
Note that the container has not been designed nor is expected to work with the file structure generated by certbot.

However, it seems possible to achieve what you want by using a deploy-hook to copy the certificate at the proper location in the directory you mapped to `/config`.  See https://certbot.eff.org/docs/using.html and search for "deploy-hook".  There is also an example.

**Comment by SoulInfernoDE** [comment]
wow thank you so much jlesage,
i'll try this asap and i'll report back if and how i could've got it working.
If it is working i would be happy if you could update your readme/instruction page about this so everyone that is using le certbot will have easy times ;-)
If i need to write a script i'll share it with you - feel free then to use it also for your readme or similiar.

**Comment by SoulInfernoDE** [comment]
A little donation is out to you as always from me ;-)

**Comment by jlesage** [comment]
Thanks!  Really appreciated :)

**Comment by jlesage** [comment]
Closing this issue.
