### ISSUE TITLE
Error when running on Raspberry PI4

### ISSUE THREAD

**Issue by spaxxilein** [jlesage/docker-jdownloader-2#36]
Hello!

When running on Raspbian Buster i get this error:

```
Step` 1/16 : FROM jlesage/baseimage-gui:alpine-3.9-glibc-v3.5.2
 ---> 3522a694a0b5
Step 2/16 : ARG JAVAJRE_VERSION=8.212.04.2
 ---> Using cache
 ---> 0606fc64ac36
Step 3/16 : ARG JDOWNLOADER_URL=http://installer.jdownloader.org/JDownloader.jar
 ---> Using cache
 ---> 083d0663b0a1
Step 4/16 : ARG JAVAJRE_URL=https://d3pxv6yz143wms.cloudfront.net/${JAVAJRE_VERSION}/amazon-corretto-${JAVAJRE_VERSION}-linux-x64.tar.gz
 ---> Using cache
 ---> c34708fdfd5a
Step 5/16 : WORKDIR /tmp
 ---> Using cache
 ---> 9600f830e23d
Step 6/16 : RUN     mkdir -p /defaults &&     wget ${JDOWNLOADER_URL} -O /defaults/JDownloader.jar
 ---> Running in 1d80a40fab2a
standard_init_linux.go:211: exec user process caused "exec format error"
ERROR: Service 'jdownloader-2' failed to build: The command '/bin/sh -c mkdir -p /defaults &&     wget ${JDOWNLOADER_URL} -O /defaults/JDownloader.jar' returned a non-zero code: 1
```

Cannot run with commandline docker nor docker-compose.

Any ideas how to fix this?

Regards,

spaxxilein

**Comment by jlesage** [comment]
Hi, this container doesn't support ARM currently... only x86-64 architecture.

**Comment by DevZiegler** [comment]
Hi I have a short question, unfortunately the Dockerfile does not work on the Raspbarry PI4. 
How does it work to redirect the GUI to a webpage?
I couldn't find anything in the dockerfile that points to it. 
I want to try to make it work on the Raspbarry and that would be unbelievable for it.
So i wouldn't have to use headless mode anymore (because myjdownloader doesn't offer all settings).

Thanks

**Comment by jlesage** [comment]
A lot of logic is also implemented in the baseimage... which also doesn't support arm :(

**Comment by Turiok** [comment]
Hi @DevZiegler ,

I'm working on it.
It's work since today on my rpi3.
But a little laggy and it seems have aliazing. 
Once I'm finished, I'll propose to @jlesage the result.

Sincerely,
Turiok

**Comment by DevZiegler** [comment]
Hi @Turiok, nice to hear.
In the meantime I also built an image from different sources for ARM systems (in my repo). But it is not that handy and it has no additional functions. Therefore a simpler solution is of course nice.
Regards DevZiegler

**Comment by Stephen988** [comment]
I guys I'm going to be crazy for find a good download manager (no torrent) for raspberry pi 4 on docker, what I can do? there are alternative to jd?

**Comment by markosc** [comment]
@Turiok  aqui hay uno para la Pi

**Comment by daniel0076** [comment]
Hi @jlesage 

I have forked this repo and modified it to support aarch64, which has been tested on my Raspberry Pi 4. [(link)](https://hub.docker.com/r/daniel0076/jdownloader-2)

Also, based on your repo `baseimage` and `baseimage-gui`, I also modified them to support aarch64 (using ubuntu20.04)
If PR is welcomed I can help with the aarch64 support.

**Comment by Matssa56** [comment]
> Hi @jlesage
> 
> I have forked this repo and modified it to support aarch64, which has been tested on my Raspberry Pi 4. [(link)](https://hub.docker.com/r/daniel0076/jdownloader-2)
> 
> Also, based on your repo `baseimage` and `baseimage-gui`, I also modified them to support aarch64 (using ubuntu20.04)
> If PR is welcomed I can help with the aarch64 support.
> 
> I think your idea of `baseimage-gui` is brilliant and I am looking forward to the support of multi-arch.

Hey I wanna use this on my rpi as well in order to replace pyload. Do you maintain your docker image? I see it wasn't been updated since quite some time.

Thanks for your help!

**Comment by daniel0076** [comment]
Hi @Matssa56,

The image is working, and I don't think it needs further update if it is working fine.
Docker images can last for a long time if there is not big changes in the software or the platform.
You can report an issue to my repo if you encounter any problem.

Thanks

**Comment by Matssa56** [comment]
> Hi @Matssa56,
> 
> The image is working, and I don't think it needs further update if it is working fine.
> Docker images can last for a long time if there is not big changes in the software or the platform.
> You can report an issue to my repo if you encounter any problem.
> 
> Thanks

Hi again,

Thanks for you speedy feedback! In that case I'll test it out on my debian install :) I was asking since I saw that your github was several commits behind this one, so maybe you stopped using it or something ;-)

**Comment by titou4307** [comment]
Hi @daniel0076
I would like to install the docker container for raspberry pi4...

I m trying to install your fork and I cannot succeed...
Docker not find your container...

Can you help me ?

Big thanks for the adaptation project for the raspberry pi4...

**Comment by jlesage** [comment]
The latest image now supports ARM (64bit).
