### ISSUE TITLE
Reverse Proxy with Caddyfile

### ISSUE THREAD

**Issue by macross5** [jlesage/docker-jdownloader-2#37]
I found the section "Routing Based on URL Path" in the readme, but I can't rewrite it to an Caddyfile like..

  redir /jdownloader /jdownloader-2/
  proxy /jdownloader jdownloader:5800 {
    transparent
  }

I get the 404 Not Found error in nginx. 

can someone help me?

**Comment by jlesage** [comment]
Were you able to find a solution ?

**Comment by macross5** [comment]
Nope, I stopped it. I made a own port for it.

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
