### ISSUE TITLE
Firewall Issue

### ISSUE THREAD

**Issue by Paytah232** [jlesage/docker-jdownloader-2#39]
Hi @jlesage, 

I recently enabled my firewall and now you docker does not connect to the network (without the firewall it works). I have allowed the 3 local docker ports I have in the firewall but it does not connect.

![image](https://user-images.githubusercontent.com/44075588/69631794-000bc200-109a-11ea-8063-48dfde3ce7e0.png)
![image](https://user-images.githubusercontent.com/44075588/69631862-144fbf00-109a-11ea-8efb-0b469aea4338.png)

Do I need to enable other ports in my Synology firewall that I'm not seeing?

**Comment by jlesage** [comment]
What is not working exactly ?  You can't access the container web UI or JDownloader can't download anything?

**Comment by Paytah232** [comment]
Jdownloader cannot access the internet. I can get into the ui fine, but it cannot update etc, so I want to know exactly what ports in need to allow and/or tcp/upd so it can access the internet.
________________________________

**Comment by jlesage** [comment]
I think you could try this: https://www.reddit.com/r/synology/comments/8fo2sj/ds918_firewall_blocking_outgoing_traffic_from/

**Comment by Paytah232** [comment]
That worked. Thanks!
________________________________

**Comment by jlesage** [comment]
Great!
