### ISSUE TITLE
Server disconnected (code: 1006)

### ISSUE THREAD

**Issue by frumpymoons** [jlesage/docker-jdownloader-2#4]
Hello,

I only use the GUI via web interface and I noticed today that the GUI shows me the error message above.
Deleting the container didn't work. I am on Debian Stretch. My Docker version is 17.09.0-ce.

JDownloader is still running because I have folderwatch configured and if I put a file in there it works.

docker inspect output
https://pastebin.com/y47mU9LV

docker logs output
https://pastebin.com/D67cStbq

processes 
```PID   USER     TIME   COMMAND
    1 root       0:00 s6-svscan -s -t0 /var/run/s6/services
   31 root       0:00 s6-supervise s6-fdholderd
  312 root       0:00 s6-supervise app
  313 root       0:00 s6-supervise xvfb
  314 root       0:00 s6-supervise x11vnc
  315 root       0:00 s6-supervise openbox
  317 app        0:00 {startapp.sh} /bin/sh /startapp.sh
  318 root       0:01 /usr/bin/Xvfb :0 -screen 0 1920x1080x24
  320 root       0:00 /usr/bin/x11vnc -display :0 -rfbport 5900 -rfbportv6 -1 -no6 -noipv6 -httpportv6 -1 -forever -desktop JDownloader 2 -cursor arrow -shared -httpdir /opt/novnc/ -nopw
  323 app        0:00 /usr/bin/openbox
  694 app        0:15 /opt/jre/bin/java -Dawt.useSystemAAFontSettings=gasp -Djava.awt.headless=false -jar JDownloader.jar
 4555 app        0:00 sleep 1
 4556 root       0:00 ps - A

**Comment by jlesage** [comment]
It seems that there is no mapping for port 5900.  You can either add one (by adding something like `-p 5900:5900` to the `docker run` command) or update your image to the latest version, which doesn't need the port 5900 to be mapped.

**Comment by frumpymoons** [comment]
Added the port and pulled the newest image, still the same error.

**Comment by jlesage** [comment]
Could you provide the docker command you use to start the container?
Also, could you give container logs you have with the new version?

**Comment by frumpymoons** [comment]
new logs
https://pastebin.com/eZCAWTwh

This is my create command
```
docker create \
--name=jdownloader \
--restart unless-stopped \
--network=docker-network \
--ip=172.18.0.5 \
-p 5800:5800 \
-p 5900:5900 \
-v /var/opt/docker/jdownloader:/config \
-v /mnt/share:/output \
-e USER_ID=1001 \
-e GROUP_ID=1001 \
-e TZ=Europe/Berlin \
-e DISPLAY_WIDTH=1920 \
-e DISPLAY_HEIGHT=1080 \
jlesage/jdownloader-2:latest

**Comment by jlesage** [comment]
Which browser are you using?  Can you try to clear the cache and/or try another browser?

**Comment by frumpymoons** [comment]
I feel dump now... thanks clearing the cache deleting cookies worked.

**Comment by jlesage** [comment]
Hey no worries :)  Happy to see that it's now working.
