### ISSUE TITLE
Unable to stop the container

### ISSUE THREAD

**Issue by ggogel** [jlesage/docker-jdownloader-2#40]
Always when I'm trying to stop or restart the container it's stuck in the state "syncing disks". The volume is a path on the hosts root partition, so nothing fancy. 

I can then kill the container by looking up it's process ID but even after recreating, I can't start it anymore because then it's stuck on startup...

The only resolution to this issue is to restart the whole host, which is pretty annoying.

```
[root@srv01 ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
[services.d] stopping services
[services.d] stopping app...
[jdsupervisor] Terminating JDownloader2...
[services.d] stopping statusmonitor...
[services.d] stopping openbox...
[services.d] stopping logmonitor...
[services.d] stopping x11vnc...
caught signal: 15
12/12/2019 11:17:30 deleted 40 tile_row polling images.
12/12/2019 11:17:30 Restored X server key autorepeat to: 1
[services.d] stopping xvfb...
[services.d] stopping nginx...
[services.d] stopping certsmonitor...
[services.d] stopping s6-fdholderd...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
```

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing... 
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing... 
```

**Comment by jlesage** [comment]
Do you have the same issue if you don't map any volume?

**Comment by martinhpunkt** [comment]
Hi,

similar problem, but on my side the container stops immediatly. The issue does NOT appear when I don't map a volume.

My setup is a little bit different though: FreeNAS 11.3 with Rancher and an nfs mounted volume to the Rancher host to provide persistant volumes from the NAS.

Which leads me to the question if this could be related to permissions. The folders /config and /output are being created.

Any help appreciated!

KR

**Comment by jlesage** [comment]
If you don't have issue when you don't map a volume, then it is probably related to permissions.  Did you adjusted `USER_ID` and `GROUP_ID` variables?
Also, using NFS adds another level of permissions.  Make sure to verify this part...

**Comment by ggogel** [comment]
Yes this issue only appears when mounting a volume. I have local paths and smb shares provided by auto-fs mounted to the container. Like I described, the issue also occurs with local paths only. I've running several other containers, which have mounted volumes in the exact same manner without issues on stopping. I'd reckon that JDownloader doesn't give up the lock on a certain file and therefore the container can't unmount the volumes.

**Comment by jlesage** [comment]
Problem should not longer be relevant with the latest image, since S6 is not used.
