### ISSUE TITLE
403 Forbidden error in browser webUI

### ISSUE THREAD

**Issue by AntonDF** [jlesage/docker-jdownloader-2#41]
I'm getting a 403 forbidden error when I try to connect via the browser webUI, but it runs fine through VNC. I'm running the container on Openmediavault, x64 arch.
Any idea why i'm getting this error?
thanks !

**Comment by jlesage** [comment]
Looks like you are not using the right ip/port to connect ?
What is the configuration of your container?

**Comment by thenexus7** [comment]
> Looks like you are not using the right ip/port to connect ?
> What is the configuration of your container?

Hi jlesage! First of all thanks for your work, great Docker image! 

I also got the same error. I'm using "Host" network settings (Portainer) with the 5800 port setup according your ports section... VNC works perfectly but no way to access the web interface using http://IP:5800 

I have a strange feeling I'm missing something simple here :)

**Comment by jlesage** [comment]
Are you access the web ui via the IP or via a DNS name?
Can you share the config of the container (`docker inspect <container name>`)?

**Comment by AntonDF** [comment]
i could resolve the issue, the problem came from my OMV configuration. I had a custom shared folder for docker which didn't have the right permission.

Anyway, thank you for your incredible work on your docker images 👍
