### ISSUE TITLE
Copy and paste Chinese characters

### ISSUE THREAD

**Issue by emteedubs** [jlesage/docker-jdownloader-2#46]
Hi, I'm running this with the CJK=1 environment variable enabled with the WenQuenYi Zen Hei font. I'm able to see Chinese filenames and paths in the app, but I cannot copy Chinese characters onto the app's clipboard to then be pasted in the application. Anytime I paste Chinese characters, it copies as random symbols in the app.

I tried connecting through VNC and through the browser, same situation. Is there a workaround to this?

**Comment by jlesage** [comment]
If the issue is seen with both a VNC client and the browser, it may be a limitation of the VNC protocol.
If you copy something inside the app, does it appear correctly in the clipboard ?

**Comment by emteedubs** [comment]
Thanks for the reply. Yes if I copy Chinese characters from within the app, they can be pasted it just fine. That's my current workaround I'm using. But it's not the most convenient and was hoping there was a solution to this. It seems like you may be correct that there were some limitations on unicode clipboard support in VNC. But it seems like a number of front end VNC apps have implemented extensions to fix this. An example of their PR can be found here: https://github.com/TigerVNC/tigervnc/issues/20

I'll close the issue for now. But not sure if there's a fix you can implement within the container at least to enable it for the web browser view.
