### ISSUE TITLE
DNS problem running docker image

### ISSUE THREAD

**Issue by zensbert** [jlesage/docker-jdownloader-2#47]
Hi,
i am running your docker image under a synology nas; but i have problems getting DNS to work. I created a new network for the container, since i need it to run on a different network (already other docker image running on synology nas ip):
`docker network create -d macvlan --subnet=192.168.125.0/24 --ip-range=192.168.125.2/32 --gateway=192.168.125.1 -o parent=bond0 NAME`
The docker image is reachable on the assigned network (single ip in this case) but jdownloader is not online. I guess its an dns problem since i cant ping on named hosts but ips work.
i tried many configurations i found on the web like:
https://blog.unltd-networx.de/synology-diskstation-docker-dns/
https://l-lin.github.io/post/2018/2018-09-03-docker_ubuntu_18_dns/
but i cant get it to work, what am i doing wrong?
Many thanks,
Thomas

**Comment by jlesage** [comment]
Did you try to set the `--dns` option ?
https://docs.docker.com/config/containers/container-networking/#dns-services

**Comment by zensbert** [comment]
I can not specify directly the run paramaters on synology (at least in the GUI); but i am able to adjust the environment variables:

![2020-04-11 08_00_53-Login](https://user-images.githubusercontent.com/44064954/79036654-af20e400-7bca-11ea-8847-20cf2e409118.png)

This doesn´t seem to have any effect. In my
/volume1/@docker/containers/CONTAINERID/resolv.conf the nameserver is still 127.0.0.11.
Changing the values doesnt change anything.

Is there a way to change the run parameters for this container on synology? is there a config file i can adjust? Thanks..

**Comment by zensbert** [comment]
My bad, i mistyped the GW-IP in the network configuration. Sorry for bothering, keep up the good work :)
