### ISSUE TITLE
Auto Extract folder

### ISSUE THREAD

**Issue by spartansj** [jlesage/docker-jdownloader-2#48]
hi.
I'm using OMV5 azul and installed the docker.Config and Download location is fine.I have volume :
/srv/dev-disk-by-label-VOLUME1TB/Downloads
/srv/dev-disk-by-label-VOLUME1TB/Config/jdownloader
Everything works ok but i had to copy the sevenzipjbinding1509Linux.jar and sevenzipjbinding1509.jar file to my libs folder.
Is there any way to setup another shared folder like /srv/dev-disk-by-label-VOLUME1TB/Media/Video/Movies for the autoextract action?

**Comment by jlesage** [comment]
Yes, you can map any folder to the container.
How did you created the container ?  Via the command line?  UI ?

**Comment by spartansj** [comment]
I created via the gui.Im not experienced in cli

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by jlesage** [comment]
I don't have OMV to play with, but I think that in the container's settings, it's under the `Volumes and Bind mounts` section.

**Comment by spartansj** [comment]
Hi.ok but what is the name of the volume variable for the extraction folder.i know how to bind like for the download volume.

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________

**Comment by jlesage** [comment]
> Hi.ok but what is the name of the volume variable for the extraction folder

What do you mean by `volume variable` ?  You could provide screenshot of your settings to help.

> i know how to bind like for the download volume.

So once you have your mapping (bind), I guess you need to go in JDownloader `Archive Extactor` settings and use the container path of your mapping as the extract destination folder.

**Comment by spartansj** [comment]
Hi,
This is what I mean. I have two volume mappings:
/config and /output. What should I have for the extraction folder?

I did found in my windows installation jdownloader, a json cfg file contain this line:

"customextractionpath" : "D:\\Movies"

So, I might have to volume map /customextractionpath maybe?
Please advise.

EDIT*
OK this one worked a treat! Thank you for getting me here.
Kind regards
Giannis

[cid:image002.png@01D61C12.290CC4A0]

[cid:image001.png@01D61C10.6C5B8540]
