### ISSUE TITLE
Feature Request: Direct Remote Control with PimpMyJDownloader and Chrome

### ISSUE THREAD

**Issue by kamilj** [jlesage/docker-jdownloader-2#49]
It would be nice to see this extension in the docker package https://github.com/coxifred/PimpMyJDownloader/wiki

**Comment by kamilj** [comment]
This could significantly increase the popularity of the application.

**Comment by Protektor-Desura** [comment]
How is this any different from MyJdownloader with the MyJDownloader browser plugin?
https://chrome.google.com/webstore/detail/myjdownloader-browser-ext/fbcohnmimjicjdomonkcbcpbpnhggkip?hl=en
https://addons.opera.com/en/extensions/details/myjdownloader-browser-extension/
https://addons.mozilla.org/en-US/firefox/addon/download-with-jdownloader/

**Comment by jlesage** [comment]
I agree, MyJDownloader is the way to go and is obviously already integrated in JDownloader.
