### ISSUE TITLE
Using GUI in Browser

### ISSUE THREAD

**Issue by user2552** [jlesage/docker-jdownloader-2#5]
I'm having trouble accessing the GUI in browser after following the Quick Start. The only modification that I made was using the flag `-u <user_id>`, which shouldn't cause any problems. Any browser should work (I prefer Firefox), so I go to `http://<host_ip>:5800`, which gives me nothing. A sanity check, how is the `host_ip` determined?

**Comment by jlesage** [comment]
The `host_ip` is the IP of the machine on which you run the container.
Did you tried without the `-u` parameter?
Can you provide the container logs/output?

**Comment by user2552** [comment]
That's what I thought about `host_ip`. 

Scrutinizing the container, I realized that I was unable to get any logs because the it exits immediately. Under the unmodified quick start input, the following is the state:
```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2017-12-08T00:52:18.736657548Z",
            "FinishedAt": "2017-12-08T00:52:18.828667766Z"
        }
```

I did a sanity check, but other docker containers run fine, e.g. `docker run -ti ubuntu bash`.

Any thoughts?

**Comment by jlesage** [comment]
Run the container without the `-d` option.  It will run in foreground and you will get the output.

**Comment by user2552** [comment]
Running the command 
```
docker run --name=jdownloader-2 -p 5800:5800 -p 5900:5900 -v /docker/appdata/jdownloader-2:/config:rw -v $HOME/Downloads:/output:rw jlesage/jdownloader
```
results in the error
```
standard_init_linux.go:178: exec user process caused "exec format error"
```

**Comment by jlesage** [comment]
On which device are you running the container?  The image only supports x86_64 processors.

**Comment by user2552** [comment]
That was the problem; I was using i386.
