### ISSUE TITLE
Cannot add a premium account (Nitroflare)

### ISSUE THREAD

**Issue by Misieq74** [jlesage/docker-jdownloader-2#50]
I am trying to setup a nitroflare premium account. After I put my login data into Account manager, "Check account" dialog box is just being displayed and that's it... When I do the same on Windows. I get another dialog box saying "Enter Captcha for nitroflare.com to continue". Then the web browser window opens, autofills the captacha autmatically and the account creation process is completed.

On Synology

![nitroflare - Synology](https://user-images.githubusercontent.com/65313163/81864955-9a3ec400-956d-11ea-888d-3b2833f83881.png)

On Windows

![nitroflare](https://user-images.githubusercontent.com/65313163/81864762-59df4600-956d-11ea-8481-b1ae7eebd7fe.png)

**Comment by ahmaddxb** [comment]
Same with me

**Comment by ain-soph** [comment]
Some similar issues for me on Synology.  
On Windows, it pops up a browser windows for me to input the captcha or recognize it automatically. But in Synology Docker, it just keeps looping the `Wait for Captcha-Slot` message.  

(btw, it seems uploaded.net not working for free account?)

![image](https://user-images.githubusercontent.com/13214530/140569271-22bc87a3-7b97-416a-8bb2-13992f81c8fe.png)

**Comment by ain-soph** [comment]
> For things that required captcha, you should try to do them via MyJdownloader.

Yes, I've figured out that. I should link my docker to MyJdownloader and use the browser plugin to do that. Thanks for your response.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
