### ISSUE TITLE
Cannot Use NFS Share (volume) for config

### ISSUE THREAD

**Issue by shetubd** [jlesage/docker-jdownloader-2#53]
Hello 
I install this on ubuntu (20.04 LTS (Focal Fossa)) docker. I make Freenas nfs share via Portainer.  I use this command for run the container and jdownloader randomly restart. When I create new container without config folder that time container running properly. 

docker run -d \
    --name=jdwn \
    -p 5800:5800 \
-v freenas_jdwn:/config:rw \
	-v freenas_jdwn:/output:rw \
	-d --restart always jlesage/jdownloader-2

**Comment by jlesage** [comment]
Can you provide the container's log ?
My guess is that you have a permission issue... Do you need to set `USER_ID` and `GROUP_ID` so that the JDownloader can write to your NFS mount ?

**Comment by jlesage** [comment]
Closing the issue.  Please reopen if needed.

**Comment by DonBongJohn** [comment]
![image](https://user-images.githubusercontent.com/20537257/195885858-7175ce77-5771-4bd5-8040-c77e48288cf6.png)
