### ISSUE TITLE
Numeric keypad not working properly in VNC Viewer

### ISSUE THREAD

**Issue by SeNeOEH** [jlesage/docker-jdownloader-2#54]
I have a strange issue when using the numeric keypad. For exemple the '4' erase the previous character, the '7' erase all characters.

I have the same configuration for VNC Viewer for this container and for your handbrake one but only have the issue with this one. I have 2 instance of this docker and have the issue on both. I don't have the issue with the WebGUI though.

I'm not really sure the issue is on the container side, but I'm not sure what I can do to fix it.

Does anybody else has this issue?

**Comment by SeNeOEH** [comment]
I just tried with another vnc client (Tiger VNC) and I have exactly the same issue.

**Comment by jlesage** [comment]
Is this still an issue ?

**Comment by SeNeOEH** [comment]
It doesn't seems to be an issue anymore.
