### ISSUE TITLE
Docker not accessible

### ISSUE THREAD

**Issue by carrieresebastien** [jlesage/docker-jdownloader-2#55]
Hello,
Thanks for your docker.
I Tried to launch it and its ok 👍 

`
PiEnfant:~ # docker run --rm -d --name=jdownloader-2 -p 5800:5800 -v $HOME/jdown
loader-2:/config:rw -v /media/KINGSTON/TV:/output:rw jlesage/jdownloader-2
9ac4aee6ca4a75ce43061b420ce24224a06401602ed63f58ec8bf031ba87e8aa
`

But when in my local network, i tried to connect to the http://My_ip:5800, it can't connect.

Have you an idea ?

**Comment by jlesage** [comment]
Just to confirm: the IP you are using the one of the server running the container ?
Can you check the container's logs? `docker logs jdownloader-2`

**Comment by jlesage** [comment]
Closing the issue, please reopen if needed.
