### ISSUE TITLE
Difficulty writing files to mounted folder, which is also mounted (SMB)

### ISSUE THREAD

**Issue by jaxjexjox** [jlesage/docker-jdownloader-2#56]
Hello,

I'm a FreeNAS user.
I run a UbuntuVM, inside FreeNAS - this little VM is chock full of docker contianers now, qbittorrent, sabnzbd, etc.
The UbuntuVM, maps a path, back onto the FreeNAS, SMB share.

I have been extensively messing with these commands.
	-e PUID=0 \
	-e PGID=0 \
	-e UMASK=000 \

I have also been messing with this

    -v /mnt/SMBMOUNTbackONFREENAS/:/output:rw \
    -v /tmp/LOCALfolderMOUNTonUbuntuVM::/output2:rw \
(not real paths, just to try and explain)

Let me be clear: (this is the problem, sorry!)
**I can run the following 2 commands perfectly successfully**

sudo docker exec -i jdownloader-2 mkdir /output/blahtest
sudo docker exec -i jdownloader-2 mkdir /output**2**/blahtest

This results in a new folder being created locally inside the UbuntuVM /tmp folder (second command)
it ALSO results in a new folder being created on the SMB mounted path, back on FreeNAS (/mnt folder)

None the less, when it comes to actually downloading, I can **NOT** download to the SMB mounted folder, it will spit out an error "invalid download directory"

This is probably my fault to be clear, however - my UbuntuVM runs the following containers.
qBittorrent
SabNZBD
Couchpotato.
Medusa
(etc etc etc)
All of these docker containers, seem capable of working with /mnt/SMBMOUNTbackONFREENAS/   except jdownloader-2

Is it possible that the program isn't issuing a command with "quotes for spaces" or something? I'm kind of baffled.
Does the jdownloader command run with different permissions than other things, inside the docker container?

**Comment by jaxjexjox** [comment]
Even this command works.
 _sudo docker exec -i jdownloader-2 cp  /output/1.mp4 /output/2.mp4_

This read and wrote a new file, from the /output/ mount, over SMB.
Yet, I continue to get invalid download directory.

**Comment by jaxjexjox** [comment]
Ok now I'm spending more hours fiddling and it's not even working locally, this must be something simple, please.....

USERNAME@ubuntuvm:/$ sudo docker stop jdownloader-2 && sudo docker rm jdownloader-2 && sudo docker run -d --name=jdownloader-2     -p 5800:5800 -e PUID=1000 -e PGID=1000 -e UMASK=000 -e DISPLAY_WIDTH=1340 -e DISPLAY_HEIGHT=820     -v /dockerconfigs/jdownloader:/config:rw     -v /mnt/DownloadOnSSD/jd2:/output:rw -**v /tmp/down:/output2:rw** -v /etc/localtime:/etc/localtime --restart=unless-stopped     jlesage/jdownloader-2^C
.
.

USERNAME@ubuntuvm:/$ sudo docker **exec -i jdownloader-2 wget** https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png  **-P /output2**
Connecting to www.google.com (172.217.25.132:443)
googlelogo_color_272 100% |********************************|  5969  0:00:00 ETA
.
.

USERNAME@ubuntuvm:/$ **ls -l /tmp/down/**
total 8
-rw-r--r-- 1 root root 5969 Jul  9 21:39 googlelogo_color_272x92dp.png




Yet, jdownloader........
https://i.imgur.com/xjXBMNQ.png

Sorry I'm at my wits end, surely it's something simple?

**Comment by jlesage** [comment]
It seems that you are not using the correct variables.  `USER_ID` and `GROUP_ID` are the ones you need to set (not sure where they come from, but `PUID` and `PGID` are not used by the container).

See https://github.com/jlesage/docker-jdownloader-2#environment-variables

**Comment by jaxjexjox** [comment]
> Sorry I'm at my wits end, surely it's something simple?

There it is as simple as that!

I feel rightfully dumb but at least I tried to do my homework, I used to have no idea how to diagnose all this.
Thanks so much for the help and the hard work making it, really appreciated, hope this helps someone else.

**Comment by jlesage** [comment]
Great, happy to see it's now working!
