### ISSUE TITLE
Unexpectatedly Stopping

### ISSUE THREAD

**Issue by fallesk** [jlesage/docker-jdownloader-2#57]
> jdownloader:
        environment:
            - VNC_PASSWORD=XXXX
            - USER_ID=1000
            - GROUP_ID=1000
        restart: always
        image: jlesage/jdownloader-2
        ports:
            - 5800:5800/tcp
            - 5900:5900/tcp
        volumes:
            - /Downloads:/output
            - /docker/appdata/jdownloader-2:/config:rw

Log:

> 11/07/2020 12:24:34 Xinerama is present and active (e.g. multi-head).
11/07/2020 12:24:34 Xinerama: number of sub-screens: 1
11/07/2020 12:24:34 Xinerama: no blackouts needed (only one sub-screen)
11/07/2020 12:24:34 
11/07/2020 12:24:34 fb read rate: 801 MB/sec
11/07/2020 12:24:34 fast read: reset -wait  ms to: 10
11/07/2020 12:24:34 fast read: reset -defer ms to: 10
11/07/2020 12:24:34 The X server says there are 10 mouse buttons.
11/07/2020 12:24:34 screen setup finished.
11/07/2020 12:24:34 
The VNC desktop is:      ddfbd6c2d685:0
0
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?
The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:
    x11vnc -ncache 10 ...
One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching
11/07/2020 12:25:00 Got connection from client 127.0.0.1
11/07/2020 12:25:00   other clients:
11/07/2020 12:25:00 Got 'ws' WebSockets handshake
11/07/2020 12:25:00 Got protocol: binary
11/07/2020 12:25:00   - webSocketsHandshake: using binary/raw encoding
11/07/2020 12:25:00   - WebSockets client version hybi-13
11/07/2020 12:25:00 Disabled X server key autorepeat.
11/07/2020 12:25:00   to force back on run: 'xset r on' (3 times)
11/07/2020 12:25:00 incr accepted_client=1 for 127.0.0.1:56576  sock=10
11/07/2020 12:25:00 Client Protocol Version 3.8
11/07/2020 12:25:00 Protocol version sent 3.8, using 3.8
11/07/2020 12:25:00 rfbProcessClientSecurityType: executing handler for type 2
11/07/2020 12:25:00 created   xdamage object: 0x40002c
11/07/2020 12:25:01 copy_tiles: allocating first_line at size 41
11/07/2020 12:25:10 created selwin: 0x40002d
11/07/2020 12:25:10 called initialize_xfixes()
11/07/2020 12:25:14 got closure, reason 1001
11/07/2020 12:25:14 rfbAuthProcessClientMessage: read: Connection reset by peer
11/07/2020 12:25:14 client_count: 0
11/07/2020 12:25:14 Restored X server key autorepeat to: 1
11/07/2020 12:25:14 Client 127.0.0.1 gone
11/07/2020 12:25:14 Statistics             events    Transmit/ RawEquiv ( saved)
11/07/2020 12:25:14  TOTALS              :      0 |         0/        0 (  0.0%)
11/07/2020 12:25:14 Statistics             events    Received/ RawEquiv ( saved)
11/07/2020 12:25:14  TOTALS              :      0 |         0/        0 (  0.0%)
11/07/2020 12:25:14 destroyed xdamage object: 0x40002c
11/07/2020 12:25:14 Got connection from client 127.0.0.1
11/07/2020 12:25:14   other clients:
11/07/2020 12:25:14 Got 'ws' WebSockets handshake
11/07/2020 12:25:14 Got protocol: binary
11/07/2020 12:25:14   - webSocketsHandshake: using binary/raw encoding
11/07/2020 12:25:14   - WebSockets client version hybi-13
11/07/2020 12:25:14 Disabled X server key autorepeat.
11/07/2020 12:25:14   to force back on run: 'xset r on' (3 times)
11/07/2020 12:25:14 incr accepted_client=2 for 127.0.0.1:60550  sock=10
11/07/2020 12:25:14 Client Protocol Version 3.8
11/07/2020 12:25:14 Protocol version sent 3.8, using 3.8
11/07/2020 12:25:14 rfbProcessClientSecurityType: executing handler for type 2
11/07/2020 12:25:15 created   xdamage object: 0x40002e
11/07/2020 12:25:19 client_set_net: 127.0.0.1  0.0001
11/07/2020 12:25:20 Pixel format for client 127.0.0.1:
11/07/2020 12:25:20   32 bpp, depth 24, little endian
11/07/2020 12:25:20   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
11/07/2020 12:25:20 no translation needed
11/07/2020 12:25:20 Enabling NewFBSize protocol extension for client 127.0.0.1
11/07/2020 12:25:20 Enabling full-color cursor updates for client 127.0.0.1
11/07/2020 12:25:20 Using image quality level 6 for client 127.0.0.1
11/07/2020 12:25:20 Using JPEG subsampling 0, Q79 for client 127.0.0.1
11/07/2020 12:25:20 Using compression level 9 for client 127.0.0.1
11/07/2020 12:25:20 Enabling LastRect protocol extension for client 127.0.0.1
11/07/2020 12:25:20 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
11/07/2020 12:25:20 Using tight encoding for client 127.0.0.1
11/07/2020 12:25:21 client 2 network rate 282.1 KB/sec (4449.4 eff KB/sec)
11/07/2020 12:25:21 client 2 latency:  25.6 ms
11/07/2020 12:25:21 dt1: 0.0018, dt2: 0.0536 dt3: 0.0256 bytes: 12017
11/07/2020 12:25:21 link_rate: LR_UNKNOWN - 25 ms, 282 KB/s
[jdsupervisor] JDownloader2 no longer running.  Exiting...
[services.d] stopping services
[services.d] stopping app...
[services.d] stopping statusmonitor...
[services.d] stopping x11vnc...
caught signal: 15
11/07/2020 12:27:57 deleted 40 tile_row polling images.
11/07/2020 12:27:57 Restored X server key autorepeat to: 1
[services.d] stopping certsmonitor...
[services.d] stopping openbox...
[services.d] stopping logmonitor...
[services.d] stopping nginx...
[services.d] stopping xvfb...[services.d] stopping s6-fdholderd...[cont-finish.d] executing container finish scripts...[cont-finish.d] done.[s6-finish] syncing disks.[s6-finish] sending all processes the TERM signal.[s6-finish] sending all processes the KILL signal and exiting.

**Comment by jlesage** [comment]
Can you look at JDownloader log files ?  You can find them under the directory you mapped to `/config`.

**Comment by fallesk** [comment]
https://ufile.io/ksbhye1r

**Comment by jlesage** [comment]
Do you see the same issue if you run:
```
docker run --rm jlesage/jdownloader-2
```
If yes, can you provide the full output of the command ?

**Comment by jlesage** [comment]
Closing the issue, please reopen if needed.
