### ISSUE TITLE
ffmpeg missing/required for HLS stream

### ISSUE THREAD

**Issue by benfishbus** [jlesage/docker-jdownloader-2#6]
When attempting to download some mp4 videos, jd2 complains that it cannot download an HLS stream due to lack of ffmpeg.  Internet Archive proceeds to download anyway, but Dailymotion just fails.  I imagine PBS and many other sites will be problematic, too.  Recommendations to work around this, or can you add ffmpeg to the image?

Thanks for some well-designed containers!

**Comment by jlesage** [comment]
Thanks for reporting the issue.  Can you provide a link to a video that fails to download?

**Comment by benfishbus** [comment]
http://www.dailymotion.com/video/xq4r3c

**Comment by benfishbus** [comment]
Oh, fascinating.  I just updated the container, and now when it pops up the ffmpeg warning, it offers a button for installing ffmpeg - which seems to do the trick!
