### ISSUE TITLE
Web UI dark color background

### ISSUE THREAD

**Issue by eduarcor** [jlesage/docker-jdownloader-2#60]
Hello,
Is it possible to have a Web UI dark theme background? I mean, is more changing the color background rather than a theme.
This light background kill my eyes in the night.
Could be control via boolean environment variable or an RBG (or any other kind of color identification values) value.
Thanks

**Comment by jlesage** [comment]
Maybe these links can help?

- https://board.jdownloader.org/showthread.php?t=80551
- https://github.com/Vinylwalk3r/JDownloader-2-Dark-Theme

**Comment by eduarcor** [comment]
It is not what I am asking for.
Is not the dark theme for the Jdownloader perse (I already have it). Is just for the webUI interface background. I don't know how I can change that in any place.

**Comment by eduarcor** [comment]
Any news here?

**Comment by jlesage** [comment]
This will have to be handled by the base image.  Since you already added an issue for the base image, I think we can close this one.

**Comment by eduarcor** [comment]
Agree, awesome thanks

**Comment by xsetiadi** [comment]
hai, i try the encivoment variable DARK_MODE=1 but got error.

i try it on docker run command, -e DARK_MODE=1

is there any easy way to enable dark mode?

**Comment by jlesage** [comment]
Please provide more details. What is the error and how do you use/set the variable ?

**Comment by xsetiadi** [comment]
its fine. im forgot to add backslash at the end of environment.
