### ISSUE TITLE
Permission problem..

### ISSUE THREAD

**Issue by kekec777** [jlesage/docker-jdownloader-2#63]
Hi 

I just installed JDownload on my docker (5:19.03.12~3-0~debian-buster / OMV5 / debian 10)
But no matter what i do i cannot get it work properly.

So my docker-compose looks something like this:
      - USER_ID=1000
      - GROUP_ID=0
I have user with id 1000 and group 0 is root

So /opt/novnc permissions are root:root (from a fresh install)
drwxr-xr-x    3 root     root          4096 Apr 24  2019 app
drwxr-xr-x    1 root     root          4096 Apr 24  2019 css
drwxr-xr-x    2 root     root          4096 Apr 24  2019 fonts
drwxr-xr-x    1 root     root          4096 Apr 26 01:35 images
drwxr-xr-x    2 root     root          4096 Apr 24  2019 include
-rw-r-----    1 root     root          9970 Aug  6 12:47 index.html
-rw-r--r--    1 root     root          9955 Apr 26 01:35 index.vnc
drwxr-xr-x    1 root     root          4096 Apr 24  2019 js

and that gives me nginx error 404 / permission denied

BUT if i access the shell and execute :
chmod -R 755 /opt/novnc 

then i can access the web gui..
After the chmod:
drwxr-xr-x    1 root     root          4096 Apr 24  2019 app
drwxr-xr-x    1 root     root          4096 Apr 24  2019 css
drwxr-xr-x    1 root     root          4096 Apr 24  2019 fonts
drwxr-xr-x    1 root     root          4096 Apr 26 01:35 images
drwxr-xr-x    1 root     root          4096 Apr 24  2019 include
-rwxr-xr-x    1 root     root          9970 Aug  6 12:47 index.html
-rwxr-xr-x    1 root     root          9955 Apr 26 01:35 index.vnc
drwxr-xr-x    1 root     root          4096 Apr 24  2019 js

Am i doing something wrong?

**Comment by jlesage** [comment]
Permissions of `index.html` seem to have changed.  This also seems to be confirmed by the date of the file, which is newer than the other ones.

Do you reproduce the same problem after re-creating the container ?

**Comment by kekec777** [comment]
Hmm i just recreated (re-downloaded) but still the same issue

**Comment by jlesage** [comment]
Can you share the output of the following command:
```
docker run --rm jlesage/jdownloader-2 ls -l /opt/novnc
```

**Comment by kekec777** [comment]
Here it is (docker run --rm jlesage/jdownloader-2 ls -l /opt/novnc) :

drwxr-xr-x    3 root     root          4096 Apr 24  2019 app
drwxr-xr-x    1 root     root          4096 Apr 24  2019 css
drwxr-xr-x    2 root     root          4096 Apr 24  2019 fonts
drwxr-xr-x    1 root     root          4096 Apr 26 00:35 images
drwxr-xr-x    2 root     root          4096 Apr 24  2019 include
-rw-r--r--    1 root     root          9955 Apr 26 00:35 index.vnc
drwxr-xr-x    1 root     root          4096 Apr 24  2019 js

**Comment by jlesage** [comment]
This issue should no longer apply with the latest image.
