### ISSUE TITLE
Server Disconnect Code 1006 when using Traefik2 as Reverse proxy

### ISSUE THREAD

**Issue by rshamsz** [jlesage/docker-jdownloader-2#65]
I was using jDownloader without any issues, but for some reasons the GUI is not accessible anymore using jDownloader domain name, but IF I use IP:port assigned to the container I can access the GUI. It is clearly a Proxy issue, 
I am looking for Traefik configuration that need to be added in order to reverse proxy to this container.

- Traefikv2 as the reverse proxy
- Tried firefox,chrome,....

Thanks,

**Comment by jlesage** [comment]
Did you try to clear browser's cache to see if it helps ?

**Comment by rshamsz** [comment]
yes, did not help

**Comment by jlesage** [comment]
So what are you seeing exactly when you access the container ?

**Comment by rshamsz** [comment]
Accessing the container from proxy  >>>> jdown.mydomain.com
![image](https://user-images.githubusercontent.com/44298524/92496601-56c82f80-f1c6-11ea-95ad-915a782484ad.png)

Accessing the GUI using local IP:port
http://192.168.2.4:42522/
![image](https://user-images.githubusercontent.com/44298524/92496963-cfc78700-f1c6-11ea-8d74-bdc1f9a9e9f9.png)

An there is nothing in the log;

"
08/09/2020 11:00:11 Got protocol: binary


08/09/2020 11:00:11   - webSocketsHandshake: using binary/raw encoding


08/09/2020 11:00:11   - WebSockets client version hybi-13


08/09/2020 11:00:11 Disabled X server key autorepeat.


08/09/2020 11:00:11   to force back on run: 'xset r on' (3 times)


08/09/2020 11:00:11 incr accepted_client=5 for 127.0.0.1:60158  sock=10


08/09/2020 11:00:11 Client Protocol Version 3.8


08/09/2020 11:00:11 Protocol version sent 3.8, using 3.8


08/09/2020 11:00:11 rfbProcessClientSecurityType: executing handler for type 2


08/09/2020 11:00:12 created   xdamage object: 0x200037


08/09/2020 11:00:16 Pixel format for client 127.0.0.1:


08/09/2020 11:00:16   32 bpp, depth 24, little endian


08/09/2020 11:00:16   true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0


08/09/2020 11:00:16 no translation needed


08/09/2020 11:00:16 Enabling NewFBSize protocol extension for client 127.0.0.1


08/09/2020 11:00:16 Using image quality level 6 for client 127.0.0.1


08/09/2020 11:00:16 Using JPEG subsampling 0, Q79 for client 127.0.0.1


08/09/2020 11:00:16 Using compression level 9 for client 127.0.0.1


08/09/2020 11:00:16 Enabling LastRect protocol extension for client 127.0.0.1


08/09/2020 11:00:16 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)


08/09/2020 11:00:16 Using tight encoding for client 127.0.0.1


08/09/2020 11:00:16 client_set_net: 127.0.0.1  0.0002


08/09/2020 11:00:16 copy_tiles: allocating first_line at size 51


08/09/2020 11:00:20 created selwin: 0x200038


08/09/2020 11:00:20 called initialize_xfixes()


08/09/2020 11:00:28 client 5 network rate 940.8 KB/sec (12997.9 eff KB/sec)


08/09/2020 11:00:28 client 5 latency:  4.1 ms


08/09/2020 11:00:28 dt1: 0.0029, dt2: 0.0170 dt3: 0.0041 bytes: 16794


08/09/2020 11:00:28 link_rate: LR_LAN - 4 ms, 940 KB/s


08/09/2020 11:01:03 got closure, reason 1001


08/09/2020 11:01:03 rfbProcessClientNormalMessage: read: Connection reset by peer


08/09/2020 11:01:03 client_count: 0


08/09/2020 11:01:03 Restored X server key autorepeat to: 1


08/09/2020 11:01:03 Client 127.0.0.1 gone


08/09/2020 11:01:03 Statistics             events    Transmit/ RawEquiv ( saved)


08/09/2020 11:01:03  ServerCutText       :      1 |         8/        8 (  0.0%)


08/09/2020 11:01:03  FramebufferUpdate   :    302 |         0/        0 (  0.0%)


08/09/2020 11:01:03  LastRect            :     36 |       432/      432 (  0.0%)


08/09/2020 11:01:03  tight               :   1382 |   2066388/ 29963948 ( 93.1%)


08/09/2020 11:01:03  TOTALS              :   1721 |   2066828/ 29964388 ( 93.1%)


08/09/2020 11:01:03 Statistics             events    Received/ RawEquiv ( saved)


08/09/2020 11:01:03  PointerEvent        :    705 |      4230/     4230 (  0.0%)


08/09/2020 11:01:03  FramebufferUpdate   :    303 |      3030/     3030 (  0.0%)


08/09/2020 11:01:03  SetEncodings        :      1 |        52/       52 (  0.0%)


08/09/2020 11:01:03  SetPixelFormat      :      1 |        20/       20 (  0.0%)


08/09/2020 11:01:03  TOTALS              :   1010 |      7332/     7332 (  0.0%)


08/09/2020 11:01:03 destroyed xdamage object: 0x200037


08/09/2020 11:01:03 Got connection from client 127.0.0.1


08/09/2020 11:01:03   other clients:


08/09/2020 11:01:03 Got 'ws' WebSockets handshake


08/09/2020 11:01:03 Got protocol: binary


08/09/2020 11:01:03   - webSocketsHandshake: using binary/raw encoding


08/09/2020 11:01:03   - WebSockets client version hybi-13


08/09/2020 11:01:03 Disabled X server key autorepeat.


08/09/2020 11:01:03   to force back on run: 'xset r on' (3 times)


08/09/2020 11:01:03 incr accepted_client=6 for 127.0.0.1:60456  sock=10


08/09/2020 11:01:03 Client Protocol Version 3.8


08/09/2020 11:01:03 Protocol version sent 3.8, using 3.8


08/09/2020 11:01:03 rfbProcessClientSecurityType: executing handler for type 2


08/09/2020 11:01:04 created   xdamage object: 0x200039


08/09/2020 11:06:07 idle keyboard:   turning X autorepeat back on.


08/09/2020 11:17:44 Got connection from client 127.0.0.1


08/09/2020 11:17:44   other clients:


08/09/2020 11:17:44      127.0.0.1


08/09/2020 11:17:44 Got 'ws' WebSockets handshake


08/09/2020 11:17:44 Got protocol: binary


08/09/2020 11:17:44   - webSocketsHandshake: using binary/raw encoding


08/09/2020 11:17:44   - WebSockets client version hybi-13


08/09/2020 11:17:44 incr accepted_client=7 for 127.0.0.1:40184  sock=11


08/09/2020 11:17:44 rfbProcessClientProtocolVersion: client gone


08/09/2020 11:17:44 client_count: 1


08/09/2020 11:17:44 Client 127.0.0.1 gone


08/09/2020 11:17:44 Statistics             events    Transmit/ RawEquiv ( saved)


08/09/2020 11:17:44  TOTALS              :      0 |         0/        0 (  0.0%)


08/09/2020 11:17:44 Statistics             events    Received/ RawEquiv ( saved)


08/09/2020 11:17:44  TOTALS              :      0 |         0/        0 (  0.0%)


08/09/2020 11:17:45 active keyboard: turning X autorepeat off.


08/09/2020 11:22:46 idle keyboard:   turning X autorepeat back on.


"

**Comment by jlesage** [comment]
Can you try to access in a window in incognito/private mode ?

**Comment by rshamsz** [comment]
I tried that and it did not help

**Comment by jlesage** [comment]
Try to open the browser's console and then access the container by adding `?logging=debug` to your url (e.g. `jdown.mydomain.com/?logging=debug`).   Finally, please share the output of the console.

**Comment by rshamsz** [comment]
Error with Feature-Policy header: Unrecognized feature: 'vr'.
ui.js:62 Starting UI...
util.js:214 Safari browser: false
util.js:214 Touch interface available: true
util.js:214 >> initConnectSettings
util.js:214 << initConnectSettings
util.js:214 >> RFB.constructor
util.js:214 >> Display.constructor
util.js:214 User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36
util.js:214 Browser: webkit 537.36
util.js:214 Setting viewport to full display region
DevTools failed to load SourceMap: Could not load content for https://jdown.mydomain/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
util.js:216 Data URI scheme cursor supported
util.js:214 << Display.constructor
util.js:216 Using native WebSockets
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:214 Setting viewport to full display region
util.js:218  Msg: noVNC ready: native WebSockets, canvas rendering
Util.Warn @ util.js:218
_updateState @ rfb.js:462
RFB @ rfb.js:222
initRFB @ ui.js:151
init @ ui.js:94
start @ ui.js:63
(anonymous) @ ?logging=debug:64
j @ jquery.min.js?v=8f38053a30:2
k @ jquery.min.js?v=8f38053a30:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=8f38053a30:2
i @ jquery.min.js?v=8f38053a30:2
fireWith @ jquery.min.js?v=8f38053a30:2
fire @ jquery.min.js?v=8f38053a30:2
i @ jquery.min.js?v=8f38053a30:2
fireWith @ jquery.min.js?v=8f38053a30:2
ready @ jquery.min.js?v=8f38053a30:2
S @ jquery.min.js?v=8f38053a30:3
util.js:214 >> UI.rfbOnUpdateState: state=loaded, oldstate=disconnected, msg=noVNC ready: native WebSockets, canvas rendering
util.js:214 << UI.rfbOnUpdateState
util.js:214 << RFB.constructor
util.js:216 Loading module HideableNavbar...
util.js:216 Loading module DynamicAppName...
util.js:216 Activating module DynamicAppName...
util.js:216 Loading module Password...
util.js:216 Activating module Password...
util.js:216 Loading module Clipboard...
util.js:216 Activating module Clipboard...
util.js:216 Loading module AutoScaling...
util.js:216 Activating module AutoScaling...
util.js:214 Scaling by 1
util.js:216 Auto scaling enabled
util.js:216 Loading module Clipping...
util.js:216 Module 'Clipping' will not be activated because higher-priority module 'AutoScaling' is active.
util.js:216 Loading module Fullscreen...
util.js:216 Loading module VirtualKeyboard...
util.js:216 Loading module RightClick...
util.js:216 Activating module RightClick...
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:218 
Util.Warn @ util.js:218
_updateState @ rfb.js:462
connect @ rfb.js:243
start @ ui.js:65
(anonymous) @ ?logging=debug:64
j @ jquery.min.js?v=8f38053a30:2
k @ jquery.min.js?v=8f38053a30:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=8f38053a30:2
i @ jquery.min.js?v=8f38053a30:2
fireWith @ jquery.min.js?v=8f38053a30:2
fire @ jquery.min.js?v=8f38053a30:2
i @ jquery.min.js?v=8f38053a30:2
fireWith @ jquery.min.js?v=8f38053a30:2
ready @ jquery.min.js?v=8f38053a30:2
S @ jquery.min.js?v=8f38053a30:3
util.js:214 >> RFB.connect
util.js:216 connecting to wss://jdown.mydomain:443/websockify
util.js:216 Detected binaryType support in WebSockets
util.js:214 << RFB.connect
util.js:214 >> UI.rfbOnUpdateState: state=connect, oldstate=loaded, msg=undefined
util.js:214 << UI.rfbOnUpdateState
websock.js:292 WebSocket connection to 'wss://jdown.mydomain/websockify' failed: Error during WebSocket handshake: Unexpected response code: 500
open @ websock.js:292
_connect @ rfb.js:346
_updateState @ rfb.js:488
connect @ rfb.js:243
start @ ui.js:65
(anonymous) @ ?logging=debug:64
j @ jquery.min.js?v=8f38053a30:2
k @ jquery.min.js?v=8f38053a30:2
util.js:214 >> WebSock.onerror: [object Event]
util.js:218 WebSocket on-error event
Util.Warn @ util.js:218
(anonymous) @ rfb.js:214
(anonymous) @ websock.js:325
error (async)
open @ websock.js:323
_connect @ rfb.js:346
_updateState @ rfb.js:488
connect @ rfb.js:243
start @ ui.js:65
(anonymous) @ ?logging=debug:64
j @ jquery.min.js?v=8f38053a30:2
k @ jquery.min.js?v=8f38053a30:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=8f38053a30:2
i @ jquery.min.js?v=8f38053a30:2
fireWith @ jquery.min.js?v=8f38053a30:2
fire @ jquery.min.js?v=8f38053a30:2
i @ jquery.min.js?v=8f38053a30:2
fireWith @ jquery.min.js?v=8f38053a30:2
ready @ jquery.min.js?v=8f38053a30:2
S @ jquery.min.js?v=8f38053a30:3
util.js:214 << WebSock.onerror: [object Event]
util.js:214 >> WebSock.onclose
util.js:218 WebSocket on-close event
Util.Warn @ util.js:218
(anonymous) @ rfb.js:193
(anonymous) @ websock.js:320
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:220  Msg: Server disconnected (code: 1006)
Util.Error @ util.js:220
_updateState @ rfb.js:460
_fail @ rfb.js:530
(anonymous) @ rfb.js:209
(anonymous) @ websock.js:320
util.js:214 >> UI.rfbOnUpdateState: state=failed, oldstate=connect, msg=Server disconnected (code: 1006)
util.js:214 << UI.rfbOnUpdateState
util.js:214 << WebSock.onclose
util.js:214 >> Keyboard.allKeysUp
util.js:214 << Keyboard.allKeysUp
util.js:218 
Util.Warn @ util.js:218
_updateState @ rfb.js:462
(anonymous) @ rfb.js:513
setTimeout (async)
_updateState @ rfb.js:512
_fail @ rfb.js:530
(anonymous) @ rfb.js:209
(anonymous) @ websock.js:320
util.js:214 >> UI.rfbOnUpdateState: state=disconnected, oldstate=failed, msg=undefined
util.js:214 << UI.rfbOnUpdateState
/?logging=debug#:1 Access to manifest at 'https://accounts.google.com/o/oauth2/auth?client_id=10XXXXXXXXXX1-68cXXXXXXXXXXXXm4fnamsu7kkeqfqe9bs5o.apps.googleusercontent.com&prompt=select_account&redirect_uri=https%3A%2F%2Foauth.mydomain%2F_oauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=eb1a44e771b90a4f6e392fda94f8354b%3Agoogle%3Ahttps%3A%2F%2Fjdown.mydomain%2Fimages%2Ficons%2Fsite.webmanifest%3Fv%3Ddfc1a80561' (redirected from 'https://jdown.mydomain/images/icons/site.webmanifest?v=dfc1a80561') from origin 'https://jdown.mydomain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
accounts.google.com/o/oauth2/auth?client_id=1084402006351-68cbi4cs2o4m4fnamsu7kkeqfqe9bs5o.apps.googleusercontent.com&prompt=select_account&redirect_uri=https%3A%2F%2Foauth.mydomain%2F_oauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=eb1a44e771b90a4f6e392fda94f8354b%3Agoogle%3Ahttps%3A%2F%2Fjdown.mydomain%2Fimages%2Ficons%2Fsite.webmanifest%3Fv%3Ddfc1a80561:1 GET https://accounts.google.com/o/oauth2/auth?client_id=108440XXXXXXXX351-68cbi4cs2XXXXXXXXsu7kkeqfqe9bs5o.apps.googleusercontent.com&prompt=select_account&redirect_uri=https%3A%2F%2Foauth.mydomain%2F_oauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=eb1a44e771XXXXXXXXX94f8354b%3Agoogle%3Ahttps%3A%2F%2Fjdown.mydomain%2Fimages%2Ficons%2Fsite.webmanifest%3Fv%3Ddfc1a80561 net::ERR_FAILED

**Comment by jlesage** [comment]
This seems to be the issue:
```
websock.js:292 WebSocket connection to 'wss://jdown.mydomain/websockify' failed: Error during WebSocket handshake: Unexpected response code: 500
```

To confirm if this is generated by the proxy or the container, you can look at `log/nginx/error.log` and `log/nginx/access.log` (in the directory you mapped to `/config`) and see if new messages appear when you access the container.

**Comment by rshamsz** [comment]
I updated the Traefik docker container and do not see the error; It was a proxy issue; 
Thanks

**Comment by rsvcoder** [comment]
> Accessing the container from proxy >>>> jdown.mydomain.com ![image](https://user-images.githubusercontent.com/44298524/92496601-56c82f80-f1c6-11ea-95ad-915a782484ad.png)
> 
> Accessing the GUI using local IP:port http://192.168.2.4:42522/ ![image](https://user-images.githubusercontent.com/44298524/92496963-cfc78700-f1c6-11ea-8d74-bdc1f9a9e9f9.png)
> 
> An there is nothing in the log;
> 
> " 08/09/2020 11:00:11 Got protocol: binary
> 
> 08/09/2020 11:00:11 - webSocketsHandshake: using binary/raw encoding
> 
> 08/09/2020 11:00:11 - WebSockets client version hybi-13
> 
> 08/09/2020 11:00:11 Disabled X server key autorepeat.
> 
> 08/09/2020 11:00:11 to force back on run: 'xset r on' (3 times)
> 
> 08/09/2020 11:00:11 incr accepted_client=5 for 127.0.0.1:60158 sock=10
> 
> 08/09/2020 11:00:11 Client Protocol Version 3.8
> 
> 08/09/2020 11:00:11 Protocol version sent 3.8, using 3.8
> 
> 08/09/2020 11:00:11 rfbProcessClientSecurityType: executing handler for type 2
> 
> 08/09/2020 11:00:12 created xdamage object: 0x200037
> 
> 08/09/2020 11:00:16 Pixel format for client 127.0.0.1:
> 
> 08/09/2020 11:00:16 32 bpp, depth 24, little endian
> 
> 08/09/2020 11:00:16 true colour: max r 255 g 255 b 255, shift r 16 g 8 b 0
> 
> 08/09/2020 11:00:16 no translation needed
> 
> 08/09/2020 11:00:16 Enabling NewFBSize protocol extension for client 127.0.0.1
> 
> 08/09/2020 11:00:16 Using image quality level 6 for client 127.0.0.1
> 
> 08/09/2020 11:00:16 Using JPEG subsampling 0, Q79 for client 127.0.0.1
> 
> 08/09/2020 11:00:16 Using compression level 9 for client 127.0.0.1
> 
> 08/09/2020 11:00:16 Enabling LastRect protocol extension for client 127.0.0.1
> 
> 08/09/2020 11:00:16 rfbProcessClientNormalMessage: ignoring unsupported encoding type Enc(0xFFFFFECC)
> 
> 08/09/2020 11:00:16 Using tight encoding for client 127.0.0.1
> 
> 08/09/2020 11:00:16 client_set_net: 127.0.0.1 0.0002
> 
> 08/09/2020 11:00:16 copy_tiles: allocating first_line at size 51
> 
> 08/09/2020 11:00:20 created selwin: 0x200038
> 
> 08/09/2020 11:00:20 called initialize_xfixes()
> 
> 08/09/2020 11:00:28 client 5 network rate 940.8 KB/sec (12997.9 eff KB/sec)
> 
> 08/09/2020 11:00:28 client 5 latency: 4.1 ms
> 
> 08/09/2020 11:00:28 dt1: 0.0029, dt2: 0.0170 dt3: 0.0041 bytes: 16794
> 
> 08/09/2020 11:00:28 link_rate: LR_LAN - 4 ms, 940 KB/s
> 
> 08/09/2020 11:01:03 got closure, reason 1001
> 
> 08/09/2020 11:01:03 rfbProcessClientNormalMessage: read: Connection reset by peer
> 
> 08/09/2020 11:01:03 client_count: 0
> 
> 08/09/2020 11:01:03 Restored X server key autorepeat to: 1
> 
> 08/09/2020 11:01:03 Client 127.0.0.1 gone
> 
> 08/09/2020 11:01:03 Statistics events Transmit/ RawEquiv ( saved)
> 
> 08/09/2020 11:01:03 ServerCutText : 1 | 8/ 8 ( 0.0%)
> 
> 08/09/2020 11:01:03 FramebufferUpdate : 302 | 0/ 0 ( 0.0%)
> 
> 08/09/2020 11:01:03 LastRect : 36 | 432/ 432 ( 0.0%)
> 
> 08/09/2020 11:01:03 tight : 1382 | 2066388/ 29963948 ( 93.1%)
> 
> 08/09/2020 11:01:03 TOTALS : 1721 | 2066828/ 29964388 ( 93.1%)
> 
> 08/09/2020 11:01:03 Statistics events Received/ RawEquiv ( saved)
> 
> 08/09/2020 11:01:03 PointerEvent : 705 | 4230/ 4230 ( 0.0%)
> 
> 08/09/2020 11:01:03 FramebufferUpdate : 303 | 3030/ 3030 ( 0.0%)
> 
> 08/09/2020 11:01:03 SetEncodings : 1 | 52/ 52 ( 0.0%)
> 
> 08/09/2020 11:01:03 SetPixelFormat : 1 | 20/ 20 ( 0.0%)
> 
> 08/09/2020 11:01:03 TOTALS : 1010 | 7332/ 7332 ( 0.0%)
> 
> 08/09/2020 11:01:03 destroyed xdamage object: 0x200037
> 
> 08/09/2020 11:01:03 Got connection from client 127.0.0.1
> 
> 08/09/2020 11:01:03 other clients:
> 
> 08/09/2020 11:01:03 Got 'ws' WebSockets handshake
> 
> 08/09/2020 11:01:03 Got protocol: binary
> 
> 08/09/2020 11:01:03 - webSocketsHandshake: using binary/raw encoding
> 
> 08/09/2020 11:01:03 - WebSockets client version hybi-13
> 
> 08/09/2020 11:01:03 Disabled X server key autorepeat.
> 
> 08/09/2020 11:01:03 to force back on run: 'xset r on' (3 times)
> 
> 08/09/2020 11:01:03 incr accepted_client=6 for 127.0.0.1:60456 sock=10
> 
> 08/09/2020 11:01:03 Client Protocol Version 3.8
> 
> 08/09/2020 11:01:03 Protocol version sent 3.8, using 3.8
> 
> 08/09/2020 11:01:03 rfbProcessClientSecurityType: executing handler for type 2
> 
> 08/09/2020 11:01:04 created xdamage object: 0x200039
> 
> 08/09/2020 11:06:07 idle keyboard: turning X autorepeat back on.
> 
> 08/09/2020 11:17:44 Got connection from client 127.0.0.1
> 
> 08/09/2020 11:17:44 other clients:
> 
> 08/09/2020 11:17:44 127.0.0.1
> 
> 08/09/2020 11:17:44 Got 'ws' WebSockets handshake
> 
> 08/09/2020 11:17:44 Got protocol: binary
> 
> 08/09/2020 11:17:44 - webSocketsHandshake: using binary/raw encoding
> 
> 08/09/2020 11:17:44 - WebSockets client version hybi-13
> 
> 08/09/2020 11:17:44 incr accepted_client=7 for 127.0.0.1:40184 sock=11
> 
> 08/09/2020 11:17:44 rfbProcessClientProtocolVersion: client gone
> 
> 08/09/2020 11:17:44 client_count: 1
> 
> 08/09/2020 11:17:44 Client 127.0.0.1 gone
> 
> 08/09/2020 11:17:44 Statistics events Transmit/ RawEquiv ( saved)
> 
> 08/09/2020 11:17:44 TOTALS : 0 | 0/ 0 ( 0.0%)
> 
> 08/09/2020 11:17:44 Statistics events Received/ RawEquiv ( saved)
> 
> 08/09/2020 11:17:44 TOTALS : 0 | 0/ 0 ( 0.0%)
> 
> 08/09/2020 11:17:45 active keyboard: turning X autorepeat off.
> 
> 08/09/2020 11:22:46 idle keyboard: turning X autorepeat back on.
> 
> "

My Issue is also the same.
I am using nginx proxy manager; 
when i access through ip:port it works;
when access through domain , I also get same error.

**Comment by jlesage** [comment]
In NPM, did you enable WebSocket support for your proxy host ?

**Comment by rsvcoder** [comment]
omg, you are life saver. Thanks a lot.
It started working after enabling Websocket support.

**Comment by jlesage** [comment]
Great!
