### ISSUE TITLE
Server is not connecting - Error 1006 

### ISSUE THREAD

**Issue by manoloxxl** [jlesage/docker-jdownloader-2#66]
Hi,

I'm not able to start the Container on my. When i run the GUI i just can see an connection error 1006 and nothing else.

I'm running the Docker image on a Portainer that is running on a libreelec image.

When i check the error log i can see that i should run -noxdamage but i'm not sure where to Set the Option in Portainer (i'm not familiar with Portainer...)

Can anybody give me a hin?

Best Regards

24/09/2020 07:30:38 passing arg to libvncserver: 5900,
24/09/2020 07:30:38 passing arg to libvncserver: -desktop,
24/09/2020 07:30:38 passing arg to libvncserver: JDownloader 2,
24/09/2020 07:30:38 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 5719,
24/09/2020 07:30:38 Using X display :0,
24/09/2020 07:30:38 rootwin: 0x169 reswin: 0x800001 dpy: 0x406359e0,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 ------------------ USEFUL INFORMATION ------------------,
[xvfb] starting...,
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed,
_XSERVTransMakeAllCOTSServerListeners: server already running,
(EE) ,
Fatal server error:,
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) ,
[openbox] starting...,
24/09/2020 07:30:38 X DAMAGE available on display, using it for polling hints.,
24/09/2020 07:30:38   To disable this behavior use: '-noxdamage',
24/09/2020 07:30:38 ,
24/09/2020 07:30:38   Most compositing window managers like 'compiz' or 'beryl',
24/09/2020 07:30:38   cause X DAMAGE to fail, and so you may not see any screen,
24/09/2020 07:30:38   updates via VNC.  Either disable 'compiz' (recommended) or,
24/09/2020 07:30:38   supply the x11vnc '-noxdamage' command line option.,
24/09/2020 07:30:38 X COMPOSITE available on display, using it for window polling.,
24/09/2020 07:30:38   To disable this behavior use: '-noxcomposite',
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 Wireframing: -wireframe mode is in effect for window moves.,
24/09/2020 07:30:38   If this yields undesired behavior (poor response, painting,
24/09/2020 07:30:38   errors, etc) it may be disabled:,
24/09/2020 07:30:38    - use '-nowf' to disable wireframing completely.,
24/09/2020 07:30:38    - use '-nowcr' to disable the Copy Rectangle after the,
24/09/2020 07:30:38      moved window is released in the new position.,
24/09/2020 07:30:38   Also see the -help entry for tuning parameters.,
24/09/2020 07:30:38   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
24/09/2020 07:30:38   repaint the screen, also see the -fixscreen option for,
24/09/2020 07:30:38   periodic repaints.,
24/09/2020 07:30:38 GrabServer control via XTEST.,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 Scroll Detection: -scrollcopyrect mode is in effect to,
24/09/2020 07:30:38   use RECORD extension to try to detect scrolling windows,
24/09/2020 07:30:38   (induced by either user keystroke or mouse input).,
24/09/2020 07:30:38   If this yields undesired behavior (poor response, painting,
24/09/2020 07:30:38   errors, etc) it may be disabled via: '-noscr',
24/09/2020 07:30:38   Also see the -help entry for tuning parameters.,
24/09/2020 07:30:38   You can press 3 Alt_L's (Left "Alt" key) in a row to ,
24/09/2020 07:30:38   repaint the screen, also see the -fixscreen option for,
24/09/2020 07:30:38   periodic repaints.,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 XKEYBOARD: number of keysyms per keycode 10 is greater,
24/09/2020 07:30:38   than 4 and 195 keysyms are mapped above 4.,
24/09/2020 07:30:38   Automatically switching to -xkb mode.,
24/09/2020 07:30:38   If this makes the key mapping worse you can,
24/09/2020 07:30:38   disable it with the "-noxkb" option.,
24/09/2020 07:30:38   Also, remember "-remap DEAD" for accenting characters.,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 X FBPM extension not supported.,
24/09/2020 07:30:38 X display is capable of DPMS.,
24/09/2020 07:30:38 --------------------------------------------------------,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 Default visual ID: 0x20,
[jdsupervisor] Terminating JDownloader2...,
24/09/2020 07:30:38 Read initial data from X display into framebuffer.,
24/09/2020 07:30:38 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/7680,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 X display :0 is 32bpp depth=24 true color,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 Listening for VNC connections on TCP port 5900,
24/09/2020 07:30:38 Listening for VNC connections on TCP6 port 5900,
24/09/2020 07:30:38 listen6: bind: Address in use,
24/09/2020 07:30:38 Not listening on IPv6 interface.,
24/09/2020 07:30:38 ,
24/09/2020 07:30:38 Xinerama is present and active (e.g. multi-head).,
24/09/2020 07:30:38 Xinerama: number of sub-screens: 1,
24/09/2020 07:30:38 Xinerama: no blackouts needed (only one sub-screen),
24/09/2020 07:30:38 ,
X11 MIT Shared Memory Attach failed:,
  Is your DISPLAY=:0 on a remote machine?,
  Suggestion, use: x11vnc -display :0 ... for local display :0,
caught X11 error:,
24/09/2020 07:30:38 deleted 60 tile_row polling images.,
X Error of failed request:  BadAccess (attempt to access private resource denied),
  Major opcode of failed request:  130 (MIT-SHM),
  Minor opcode of failed request:  1 (X_ShmAttach),
  Serial number of failed request:  58,
  Current serial number in output stream:  120,
Openbox-Message: A window manager is already running on screen 0,
[services.d] stopping openbox...,
[services.d] stopping certsmonitor...,
[services.d] stopping logmonitor...,
[services.d] stopping statusmonitor...,
[services.d] stopping x11vnc...,
[services.d] stopping xvfb...,
[services.d] stopping nginx...,
[services.d] stopping s6-fdholderd...,
[cont-finish.d] executing container finish scripts...,
[cont-finish.d] done.,
[s6-finish] syncing disks.,
[s6-finish] sending all processes the TERM signal.,
[s6-finish] sending all processes the KILL signal and exiting.,

**Comment by jlesage** [comment]
What are the container settings?  Can you provide the output of `docker inspect <name of the container>` ?

**Comment by manoloxxl** [comment]
I did not configured any special. Just the network (it use host). Here ist the inspect Data:

`{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "ArgsEscaped": true,
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/init"
        ],
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=en_US.UTF-8",
            "S6_BEHAVIOUR_IF_STAGE2_FAILS=3",
            "S6_SERVICE_DEPS=1",
            "USER_ID=1000",
            "GROUP_ID=1000",
            "APP_NAME=JDownloader 2",
            "APP_USER=app",
            "XDG_DATA_HOME=/config/xdg/data",
            "XDG_CONFIG_HOME=/config/xdg/config",
            "XDG_CACHE_HOME=/config/xdg/cache",
            "XDG_RUNTIME_DIR=/tmp/run/user/app",
            "DISPLAY=:0",
            "DISPLAY_WIDTH=1280",
            "DISPLAY_HEIGHT=768",
            "S6_KILL_GRACETIME=8000"
        ],
        "ExposedPorts": {
            "3129/tcp": {},
            "5800/tcp": {},
            "5900/tcp": {}
        },
        "Hostname": "LibreELEC",
        "Image": "jlesage/jdownloader-2:latest",
        "Labels": {
            "org.label-schema.description": "Docker container for JDownloader 2",
            "org.label-schema.name": "jdownloader-2",
            "org.label-schema.schema-version": "1.0",
            "org.label-schema.vcs-url": "https://github.com/jlesage/docker-jdownloader-2",
            "org.label-schema.version": "unknown"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/config": {},
            "/output": {}
        },
        "WorkingDir": "/tmp"
    },
    "Created": "2020-09-29T16:37:11.606156143Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3933d13bfe480d76c7349b31d3e9696f33db750b7b261eec516f813e16652df5-init/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/8b187a71c94e6ed59157d84cd562b2525b143b49adff955b4e05e5a9475a77bd/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/dfeb2f0a1b0468a2f5c77056e7d3e929c86fa94ac917e169cf4c1fda6602ba6c/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/5747d4ef3c702c14d8f84cf9339982b2235459411bc286a3cae51bea5d6551f3/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/967e47131a20bccfaae18e2b9b69a72322cd46957fd3178616dfa7c0f570f127/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/982428320b5dbea3317120c40375af321a151aef4865104da5f951b051f534af/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/2c2e9abd722143ae9bf2e271088837c5b0a58235a4f72fc65c936291e52e8d1b/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/8c0d5f2a5300e2984313ef75c726e3c29568e005ab6e5eae894e7465dd9c3b1c/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/cdc7fd6b9b48a6d7abb2187f6c0fc797d282ed969d90a5602876c52c7ef33d82/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/a7fe221c567e53edac21a152e30ac3cca55d53b717b731a1df248a0017b7d4fa/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/ece168b8ecd21b07cb44226e750959fafe3d43032f94b80f19535f61e3f16f1c/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/a87c8101e4b10a2230c061e7cb57af23aab352b9baf1c3675f2501c267cb7be3/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/9919db793f59da18df4d03a5715fdbc4e076f45c36ed49f722d12f5fc1634a84/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/8d2fbafaf495aedf5daab016b6c3269b8f3080311075587d2afdf1f908aa299c/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/300a925a4ed879ef86baa16e348df90a1ff8418820c97499990cd2f87148200b/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/b073b50202450b3f5d7db5eb9786bb230884a68a54c120c086181ac035aaab41/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/aa06b4c563cded213060f581eb927a376dfe7871008b8391b5542c50497a1c16/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/88d6c8144fe0b498f57ae643e7d47892b82acd3c5cbdae7a2fba1462bb81a551/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/c029ff56f9efedeb90c1b329a9fa65d19409abd0908be7f0722b5b48743c5075/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/7a67b6f6a8e1d034f43df10b578aeb0659932d19a071ca2639fc9f527c4f3b17/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/9beb0f712c64ac5b796a261861f4d0b993efb78f1785c3b3251f3a7af364bf95/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/b6bf3d07bf932e875f7d6df938972e6ab0447a94101393cd85f2c0d249c52c5d/diff:/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/9fa1a95f0b704b77fcd2714b7ec04b2948a90837ce7e54da7911310405642341/diff",
            "MergedDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3933d13bfe480d76c7349b31d3e9696f33db750b7b261eec516f813e16652df5/merged",
            "UpperDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3933d13bfe480d76c7349b31d3e9696f33db750b7b261eec516f813e16652df5/diff",
            "WorkDir": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/overlay2/3933d13bfe480d76c7349b31d3e9696f33db750b7b261eec516f813e16652df5/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "jdownloader:/output"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "Devices": [],
        "DiskQuota": 0,
        "Dns": [],
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "Init": false,
        "IpcMode": "shareable",
        "Isolation": "",
        "KernelMemory": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "journald"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "host",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": 0,
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "no"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/containers/49b3470980464ddf2959f088be41d2673ae3643ab793182fbff96d1fa52f91f0/hostname",
    "HostsPath": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/containers/49b3470980464ddf2959f088be41d2673ae3643ab793182fbff96d1fa52f91f0/hosts",
    "Id": "49b3470980464ddf2959f088be41d2673ae3643ab793182fbff96d1fa52f91f0",
    "Image": "sha256:d223b06e88ffdbf1aa6c1b7060c756fa9ab589ae7daa9084f2b069db436b59e7",
    "LogPath": "",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/output",
            "Driver": "local",
            "Mode": "z",
            "Name": "jdownloader",
            "Propagation": "",
            "RW": true,
            "Source": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/volumes/jdownloader/_data",
            "Type": "volume"
        },
        {
            "Destination": "/config",
            "Driver": "local",
            "Mode": "",
            "Name": "6ce80260e24b5b1d73ae587891ba2c05a641f9bbfc4bad278d608ae55729a1f4",
            "Propagation": "",
            "RW": true,
            "Source": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/volumes/6ce80260e24b5b1d73ae587891ba2c05a641f9bbfc4bad278d608ae55729a1f4/_data",
            "Type": "volume"
        }
    ],
    "Name": "/jdownloader2x",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "host": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "01c647c0d948764a2328d31a28c27f22207f215906bc758a51a1a747c3030d47",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "053df3137d67041d79bf0979acd5dbe479e83347ab442ab8ae7c46e99e991a19"
            }
        },
        "Ports": {},
        "SandboxID": "4dda8dfc52db4af35d242bb75f24d0bd5d2749d924327303dfcafaacbb9beb17",
        "SandboxKey": "/var/run/docker/netns/default",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/init",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 36,
            "ResourceId": "49b3470980464ddf2959f088be41d2673ae3643ab793182fbff96d1fa52f91f0",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/storage/.kodi/userdata/addon_data/service.system.docker/docker/containers/49b3470980464ddf2959f088be41d2673ae3643ab793182fbff96d1fa52f91f0/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 11068,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2020-09-29T16:37:11.837236083Z",
        "Status": "running"
    }
}`

**Comment by jlesage** [comment]
The X server is not able start:
```
[xvfb] starting...,
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed,
_XSERVTransMakeAllCOTSServerListeners: server already running,
(EE) ,
Fatal server error:,
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) ,
```
Looks like the `/tmp` could be shared with the host, but I don't see it in the provided data...
Can you provide the output of the following commands:
```
docker exec <container name> ls -la /
docker exec <container name> ls -la /tmp/
```

**Comment by steesti** [comment]
I had the same issue, was poking around in the dark and fixed it by removing ubuntu-mate-core via tasksel

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
