### ISSUE TITLE
the container does not start automatically

### ISSUE THREAD

**Issue by cruix89** [jlesage/docker-jdownloader-2#67]
hello friends, I'm using the docker in the open media vault, and every time I restart the server, when starting the jdownloader container it is stopped, 
everyone else starts automatically, I have to manually start the jdownloader container, 
is there any configuration for this? 
since already thank you very much and congratulations for the excellent work

**Comment by jlesage** [comment]
Did you set the container restart policy to "always" ?

**Comment by TDS1995** [comment]
Hello, I have the same problem as cruix89. I tried it both with the restart policy always and also a self created systemd service. Both are ignored and the container don't start automatically.

Unfortunately I don't have much experience with Docker and don't know where to look for the error. Can you give me a tip?

**Comment by jlesage** [comment]
Are you also using open media vault ?

**Comment by jlesage** [comment]
Closing the issue.  Please reopen if needed.
