### ISSUE TITLE
YouTube Codec AV1 / 4K + 8K support

### ISSUE THREAD

**Issue by Cooly0** [jlesage/docker-jdownloader-2#69]
Hello, I just noticed the Win10 version of JD2 is able to detect & download AV1; 

However, the Docker Image on Synology with full updates as of 2020/11/24 only detects VP9. As far as high-res youtube goes I believe VP9 & AV1 (AV01) are solely for HD/UHD+ levels.

Here is a sample Link: https://www.youtube.com/watch?v=C50VDJ3dUX4&list=PLhpbZcOKxtO1KjylTwx2GaRn-CQD4RzyD&index=7

https://www.youtube.com/watch?v=VMq9-GXAchA&list=PLhpbZcOKxtO1KjylTwx2GaRn-CQD4RzyD&index=6

Any ideas?

**Comment by jlesage** [comment]
I think this is now working.  With the link you provided, I can choose the AV1 variant in 8K.

**Comment by Cooly0** [comment]
Sorry, I didn't see you post from last year. 
I agree I see 8K, but I don't see 8k/AV1 in an MKV container. Are you able to add this too?

**Comment by jlesage** [comment]
I confirmed that the behaviour is the same on a "normal" JDownloader installation on Linux.  Thus, you are probably better to ask on the JDownloader forum (https://board.jdownloader.org) if you would like this new feature to be implemented.
