### ISSUE TITLE
Need to define internal ports 5800 and 5900 as variables

### ISSUE THREAD

**Issue by dflat1** [jlesage/docker-jdownloader-2#70]
I find it is necessary to define the internal ports 5800 and 5900 as variables because docker's port forwarding cannot work in my use case.  I have setup a VPN container which directs all its traffic to the VPN.  When setting up docker-jdownloader-2 to use the vpn container's network (eg.  "docker run -it --net=container:vpn -d jlesage/docker-jdownloader-2") along with jlesage/firefox container, there is a port conflict for these two ports (5800 and 5900).  As the containers are internally using the same network as the vpn container, docker's port forwarding won't fix this issue.  Only by defining the jdownloader and firefox ports differently when they are started can fix this issue.

Can the internal ports 5800 and 5900 be defined as variables?

Thanks!

**Comment by qdm12** [comment]
We need this over here https://github.com/qdm12/gluetun/issues/343 as well please! I'm happy to do a PR but I'm not sure where these port values is set really. Thanks for any clarification 😉

**Comment by dflat1** [comment]
I’ve been looking at this issue but haven’t tested it yet, but I believe the http port 5800 is set in nginx.conf.  The VNC port 5900 I believe is an option of “x11vnc”.  I think it should be set via -rfbport, but again I haven’t tested this.

**Comment by jlesage** [comment]
These ports are currently hard-coded in the base image.  However, I'm working on a new version of the base image that will allow to configure these ports.

**Comment by jlesage** [comment]
This is now supported with the latest image.
