### ISSUE TITLE
Unable to start server - error 1006

### ISSUE THREAD

**Issue by dn8sh6HY** [jlesage/docker-jdownloader-2#71]
Hi, I have jdownloader 2 running through Portainer/Docker on OpenMediaVault V. I have a fairly simple setup but I haven't been able to get it to run - jdownloader quits almost immediately. It's not clear to me why. I've attached the log which is pretty brief.
[_jdownloader_logs.txt](https://github.com/jlesage/docker-jdownloader-2/files/5935677/_jdownloader_logs.txt)

**Comment by jlesage** [comment]
Can you provide the log file at `logs/output.log`, under the directory you mapped to `/config` ?

**Comment by dn8sh6HY** [comment]
I was able to fix this a few days after posting but unfortunately I don't remember what I did.
