### ISSUE TITLE
synology jdownloader - plugin not grabbing links from uloz.to

### ISSUE THREAD

**Issue by danuwaanalihi** [jlesage/docker-jdownloader-2#73]
Just tried to install jdownloader in docker2. Seems to work but I am using only 1 service - uloz.to as file host. I can't get browser extension to grab link (neither premium nor free) that would transfer it to client in synology. If I paste it manually in linkcollector - it will start easily. Any idea what could I be missing? Other links like youtube videos or so work.

**Comment by jlesage** [comment]
Are you using the MyJDownloader extension (https://my.jdownloader.org/apps/) ?  Normally, you just need to login to your account on both the extension and JDownloader2 and it should work fine.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
