### ISSUE TITLE
[jdsupervisor] JDownloader2 not started yet.  Proceeding...

### ISSUE THREAD

**Issue by marcal** [jlesage/docker-jdownloader-2#74]
Hello,

I have tried to install this docker image in a truenas scale server.
Here is what I have done so far
1) take back an existing docker instance from another computer (zfs send...)
2) Make a completely new image (as the command line says with no volume)
3) Make volumes for the user marc uid 1000 gid 1000
mkdir /docker/appdata/jdownloader-2
chown marc /docker/appdata/jdownloader-2

mkdir /tmp/Downloads
chown marc /tmp/Downloads

docker run -d --name=jdownloader-2 -p 5800:5800 -v /docker/appdata/jdownloader-2:/config:rw -v /tmp/Downloads:/output:rw jlesage/jdownloader-2

I have also tried to change the ports with no success
Here is the docker log.
Can you please tell me what is wrong? What am I missing? the exact command line works on another linux Debian
Thank you
Marc
[jd2log.txt](https://github.com/jlesage/docker-jdownloader-2/files/6056988/jd2log.txt)

**Comment by jlesage** [comment]
What is the issue exactly ?  I don't see problems in your log file...

**Comment by marcal** [comment]
Hello,
Sorry, I forgot my question :( 
After 5 minutes, there is still no answer from JDownloader2 (http://IP:5800 gives nothing). I used the directory (config) of another computer too and the instance is not seen with myjdownloader too.

**Comment by jlesage** [comment]
What are you getting exactly when connecting ?

**Comment by marcal** [comment]
Hello,
Thank you for the help.
When I start a connection (web browser)
I have 
```
Désolé, impossible d’accéder à cette page.192.168.1.84 a refusé la connexion.
Effectuez une recherche sur le web pour 192 168 1 84
ERR_CONNECTION_REFUSED
```
With VNC (port 5900) I have an error (when I specify a password)
Cannot establish connection. Are you sure you have entered the correct network address and port number if necessary.

**Comment by marcal** [comment]
Hello,

I believe that I have seen the reason of the problem. Using the parameter  --network=host all is fine so it is a problem with my bridge network that doesn't work correctly.

Sorry for the disturbance.

**Comment by jlesage** [comment]
The bridge network should work well when using the `-p 5800:5800` parameter.
You can try to run `docker inspect <name of the container>` to see if the port mapping is properly set.

**Comment by marcal** [comment]
Hello,
Thank you for the help.

It seems that by default True Truenas scale doesn't allow the bridge to work. You have to change a settings to make it work).
(https://www.truenas.com/community/threads/docker-containers-have-no-outbound-internet-connectivity.91148/)
Thank you and sorry for the time lost

**Comment by marcal** [comment]
It is a problem with the configuration of truenas scale by default
