### ISSUE TITLE
Stuck at "VNC Handshake"

### ISSUE THREAD

**Issue by ehetteNandaYo** [jlesage/docker-jdownloader-2#76]
For some reason this hapenns now and it never loads

![image](https://user-images.githubusercontent.com/62739770/112820105-4a68ce80-9053-11eb-882c-421f0ffa9c95.png)

I tried to update but nothing, what can I do ?

**Comment by jlesage** [comment]
Are you accessing the container directly or through a reverse proxy ?
Did you try to clear your browser cache or access the container via a private/incognito window ?

**Comment by ehetteNandaYo** [comment]
by IP Directly, it fixed itself today.

I did try different browsers or icognito mode, it only worked in edge, weird is that I didnt use it on the other browsers but the problem was present in all of them except edge.

anyway, Thanks!
