### ISSUE TITLE
Auto setup MyJdownloader

### ISSUE THREAD

**Issue by Protektor-Desura** [jlesage/docker-jdownloader-2#77]
It would be nice to be able to automatically setup MyJdownloader from environmental varibles when setting up the docker.  You can find scripts to do this already here:
https://github.com/jaymoulin/docker-jdownloader
He already set it up but doesn't have some of the nice features that your docker has. So if you could add these small scripts to your dockerfile then we could use environmental variables to auto setup MyJdownloader which would be nice.

**Comment by jlesage** [comment]
This is now supported with the latest image.
