### ISSUE TITLE
ffmpeg support

### ISSUE THREAD

**Issue by hardwareadictos** [jlesage/docker-jdownloader-2#78]
hey!! 

Is is posible to add support for ffmpeg conversion for YouTube VP9 downloaded files?

Thanks in advance :)

**Comment by jlesage** [comment]
Is this something that is normally done by JDownloader?  Or you mean adding this functionality on top of JDownloader ?

**Comment by Projekt95** [comment]
Afaik there is a built-in ffmpeg plugin that comes with the JD2 installation that lets you convert media files after the download. 
Comes pretty handy if you download songs from YT and want it in .mp3 instead of .m4a for example. 
Not sure if you can select the output file type in the web interface though. You can definitly in the desktop application.

**Comment by TechGeeksIO** [comment]
Any updates on this? Would be great to have this plugin enabled.

Thank you!

**Comment by jlesage** [comment]
Sorry I didn't find how to use this feature.  Could you explain how you use it?

**Comment by kimdre** [comment]
@jlesage This is the mentioned feature. 

![image](https://user-images.githubusercontent.com/27567533/164985498-2b706c69-596b-4a8b-8985-e1b685a3c7c5.png)

**Comment by TechGeeksIO** [comment]
I tried it with a Youtube Video which seems to work fine, but a soon as I want to download a .m3u8 file it shows as offline. If I try the same link on my WIndows PC it works perfectly fine.

So, I'm not 100% sure if this is a issue with ffmpeg or not since youtube works.

**Comment by jlesage** [comment]
Could you share the link of a video that doesn't work, along with the variant you used ?

The variants I tried (for https://www.youtube.com/watch?v=dQw4w9WgXcQ) did work for me.

**Comment by jlesage** [comment]
BTW, ffmpeg is already part of the image, so the issue might be something else.

**Comment by TechGeeksIO** [comment]
Ok I think I was able to fix it.

The following two links helped: 
https://support.jdownloader.org/Knowledgebase/Article/View/download-from-video-audio-streaming-websites

https://support.jdownloader.org/Knowledgebase/Article/View/fix-jdownloader-installation

Deleting the following files/folders seems to fix it, I think recreating the container would also help:
Files: Core.jar
Folders: tmp, update

jlesage, thanks for your quick feedback and the great containers, love them!

**Comment by jlesage** [comment]
Thanks for the update!

I will close the issue for now, please re-open if needed.
