### ISSUE TITLE
Include OpenSSH package in Docker image?

### ISSUE THREAD

**Issue by nogaff** [jlesage/docker-jdownloader-2#79]
Would it be possible to either add the OpenSSH package to the main docker image, or provide another branch of the image that includes it?

This would be very handy for running commands on the host machine via JDownloader's event scripter plugin.

For example, I've built my own image with OpenSSH included which I'm running on a Synology NAS, and I've configured an event script to trigger after archive extraction, which connects to the host and runs `synoindex -R /path/to/downloads/directory` to reindex the contents of JDownloader's output folder, making the new files immediately available in the Synology's DLNA server.

**Comment by jlesage** [comment]
You can install any package using the `INSTALL_EXTRA_PKGS` environment variable.  See
https://github.com/jlesage/docker-jdownloader-2#environment-variables

**Comment by nogaff** [comment]
Oh, that's perfect! Apologies for not noticing the variable myself.
