### ISSUE TITLE
On synology: no longer starting 

### ISSUE THREAD

**Issue by michabbb** [jlesage/docker-jdownloader-2#83]
hi there,

I don't know if my issue is related to #66
but today, after months, the container restarted all the time and I am unable to identify the issue in the logs.
a full restart of the nas didn't help and resetting the container either. 

hopefully, someone is able to see anything in my logs.

https://ufile.io/fhhdxoy3

thanks for any help!

**Comment by jlesage** [comment]
Is this still an issue ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
