### ISSUE TITLE
Toggle window server 

### ISSUE THREAD

**Issue by jeff-geoff** [jlesage/docker-jdownloader-2#84]
EDIT:

that should be “toggle window server”
My apologies

Would it be possible to set a flag to choose which access methods are enabled e.g. via web, vnc, myjdownloader, or a combination thereof but not *all*?

running the window server consumes resources that aren’t necessary if only using my jdownloader, and securing both http and VNC is a pain if I only really need one of the two.

I run on synology, and my preferred configuration is the same as the synology package, which is headless with access only by my jdownloader and therefore very lean. But I don’t think there is a way to duplicate this setup

**Comment by jlesage** [comment]
With the latest image, JDownloader can run un "headless" mode.
