### ISSUE TITLE
HELP QUESTION: Alternate File Types

### ISSUE THREAD

**Issue by qwksilver** [jlesage/docker-jdownloader-2#87]
I want to add a custom filetype.  It doesn't process links, even direct download links, to this file ending.  I've searched high and low and can't find info on if this is even possible.  So asking here seems to be a last ditch effort to talk to those in the know.

so if i can tell it that say .xyz should be downloaded, can I?  thanks.

**Comment by jlesage** [comment]
Did you try to ask this question on the JDownloader forum ?  I think you should have better luck there.

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
