### ISSUE TITLE
Use /output on a CIFS

### ISSUE THREAD

**Issue by capo42** [jlesage/docker-jdownloader-2#9]
Hello

Thanks for your fantasic work. Everything works like a charm.
But now i want to place the /output volume to a Mounted cifs volume.
As i see you do a chown in the jdownloade2.sh.
That wont work on a CIFS volume. 
Any Ideas on this issue?

Regards
Michele

**Comment by jlesage** [comment]
Maybe it's a permission issue?  Are you able to verify if files can be created under `/storage` when mapped to a CIFS volume?

**Comment by capo42** [comment]
Hello

Thanks for the fast reply.
Jep, with Storage does it work!
Here the commands i use, /mnt/zarni_Dockerfiles are the cifs Volume i mounted on the host.
Works:
docker run -d \
    --name=jdownloader-2 \
    -p 5800:5800 \
    -v /var/lib/docker/volumes/JD2_Config:/config:rw \
    -v /var/lib/docker/volumes/JD2_Output/:/output:rw \
    -v /mnt/zarni_Dockerfiles/JDownloader_Storage/:/storage:rw \
    jlesage/jdownloader-2

Does not work:
docker run -d \
    --name=jdownloader-2 \
    -p 5800:5800 \
    -v /var/lib/docker/volumes/JD2_Config:/config:rw \
    -v /mnt/zarni_Dockerfiles/JDownloader_Downloads/:/output:rw \
    -v /var/lib/docker/volumes/JD2_Storage/:/storage:rw \
    jlesage/jdownloader-2

Thanks
Michele

**Comment by jlesage** [comment]
Sorry, I meant `/output`.

Is the following command working?  It should create the file `testfile` under `/mnt/zarni_Dockerfiles/JDownloader_Downloads/`.

```
docker run --rm -v /mnt/zarni_Dockerfiles/JDownloader_Downloads/:/output:rw jlesage/jdownloader-2 touch /output/testfile
```

**Comment by capo42** [comment]
Jep, that works.
I assume its the chown command you use in the jdownloader2.sh skript.

**Comment by jlesage** [comment]
If `chown` fails, downloads could also fail due to incorrect permissions.

Did you verified that everything works well if you disable the `chown`?

**Comment by capo42** [comment]
Hey there and sorry for the late reply.
I Forked your Git, edited the shell skript jdownloader2.sh (removed the chown).
E voila, i was able to start the Container without any problems wher the /output was bound to the mounted cifs.

**Comment by jlesage** [comment]
Thanks for the confirmation.  I guess that you can also download stuff without issue?

**Comment by capo42** [comment]
Jep. no Problem with that.
Will you make a change? Or should i stay with the Fork?

Regards
Michele

**Comment by jlesage** [comment]
Try the latest version, in which the issue should be fixed.

**Comment by capo42** [comment]
Jep. working like a charm!
Thanks!

**Comment by recklessnl** [comment]
@capo42 Do you have any issues with CRC checks failing when download to a CIFS share? See #27 - I can't get downloading straight to a CIFS share to work due to CRC check errors and super sluggish, freezing GUI. What's your setup like? Are you mounting it in fstab?
