### ISSUE TITLE
external hd

### ISSUE THREAD

**Issue by ph3de** [jlesage/docker-jdownloader-2#91]
Hi
is it not possible to use an external hard disk to the nas as a repository for the dl?

on my qnap i'm trying to use this path /share/external/DEV3502_2/JD but it does not work.

I also tried to follow this guide but the folders of the usb disks are not mapped

tnx

**Comment by jlesage** [comment]
Why it didn't work?  It should be possible to map any folder from the host (QNAP) to the container.

**Comment by ph3de** [comment]
I don't know why
I have tried with both ssh path and with http url

the first is /share/external/DEV3502_2/download
the second is //nas0da242/DL/download

but in both cases in the JD folder setting menù the url of share folder is  not visible, i can access only at container folders
![image](https://user-images.githubusercontent.com/96948177/148373388-0b7d0c1c-78a3-4c99-b9df-16e6cf284483.png)

**Comment by jlesage** [comment]
You need to use volume mappings to expose folder(s) of the host to the container.  If you use the cli to create the container, it's the `-v` parameter.  If you use the QNAP Container Station, it's under the `Volume` tab.

**Comment by ph3de** [comment]
I understood my mistake: I was looking at the download folder in the JD's configuration menu which has as folder / output and I thought it was wrong;)

However, it seems to me that if I restart the container the config and output folders are changed

**Comment by jlesage** [comment]
You mean the mappings are changed ?  Changed to what?

To better help you, maybe you could share your container configuration, or the way you created it.

**Comment by ph3de** [comment]
the automatic start of the container is not configured by default so they have to configure it later from the container station. to do this it is necessary to restart the container and then the config and output folders are configured in two sub-folders of the container station installation folder.

in the container settings the list of the folders configured before and after remains

![container](https://user-images.githubusercontent.com/96948177/149020864-af51cad0-a692-4085-b556-23792a0ff452.png)

**Comment by jlesage** [comment]
Mappings look wrong.  Is the first listed path in table the host side or the container side ?

**Comment by ph3de** [comment]
host side

**Comment by jlesage** [comment]
Closing this issue. Please re-open is needed.
