### ISSUE TITLE
Captchas can not be solved via smartphone

### ISSUE THREAD

**Issue by updatefreak** [jlesage/docker-jdownloader-2#93]
Hello developer,

for me it is not possible to solve Captchas via smartphone (android). (there is no key board for letters, numbers)
On Windows Browser this is no problem.

Android Browser: Chrome and Samsung Browser (Internet) tested

**Comment by jlesage** [comment]
When accessing the UI from a browser, you should have a button (in the top banner) to show the virtual keyboard.  Do you see it ?

**Comment by jlesage** [comment]
Closing this issue, please re-open if needed.
