### ISSUE TITLE
Docker deployment - first run getting password required

### ISSUE THREAD

**Issue by mattkbach** [jlesage/docker-jdownloader-2#94]
Hello

Just pulled the latest build (jlesage/jdownloader-2:latest). When going to the url (http://IP:5800), I am immediately prompted with a 'Password required' box. Tried to google what the default password might be but not having any luck. I did set a VNC_PASSWORD but I assume that's not it but I did try anyways with no luck. This is my first time deploying jdownloader so I'm not sure what the expected behavior is. 

Thanks

**Comment by jlesage** [comment]
If you have set `VNC_PASSWORD`, it's this password that you need to enter.

Also note that this password cannot be longer than 8 characters.

**Comment by jarrodhroberson** [comment]
what is the default VNC_PASSWORD? I did not set one, so I have no idea what it is.

**Comment by jlesage** [comment]
By default, there is no password.  The password you set with this variable is asked when connecting to the UI.

Are you sure it's the VNC password that is asked?

**Comment by jlesage** [comment]
Closing the issue.  Please re-open if needed.
