### ISSUE TITLE
problem decoding and renaming

### ISSUE THREAD

**Issue by CeskoFTB** [jlesage/docker-jdownloader-2#95]
As you can see, the decoding of the file is done but without renaming and a file is persisting.

![Screenshot_2022-01-27-12-58-27-658_org appwork myjdandroid](https://user-images.githubusercontent.com/97540714/151355333-b1f2f89d-d37e-45ba-9209-71f5f7dc18df.jpg)
![Screenshot_2022-01-27-13-00-27-171_com cxinventor file explorer](https://user-images.githubusercontent.com/97540714/151355341-901b8c5d-b192-4dc4-a8bb-58df58162d04.jpg)

**Comment by jlesage** [comment]
Is this still an issue ?

**Comment by jlesage** [comment]
Closing this issue.  Please re-open if needed.
