### ISSUE TITLE
Tooltips not shown

### ISSUE THREAD

**Issue by etherfry** [jlesage/docker-jdownloader-2#96]
Tooltips are not shown, when accessing via VNC/WEB.

I looked at advanced options, to see if tooltips were disabled, but they aren't.

Could it be a problem of the makeshift desktop environment? Or could it be a question of feature support in vnc clients?

**Comment by jlesage** [comment]
You mean tooltips that appear when you let the mouse pointer over a button ?  It's working for me...

Do you have a specific example where it doesn't work ?

**Comment by etherfry** [comment]
You're right. It just took longer than I expected. Will have to play around with advanced settings to fix this.

Thanks for your help.
