### ISSUE TITLE
Shell for ip information

### ISSUE THREAD

**Issue by annualstatement** [jlesage/docker-jdownloader-2#97]
Hi, 

I'm trying to find out what the IP is within shell, but I can't seem to get it.  I Tried using ifconfig and curl ifconfig.io but doesn't work. I'm trying to verify if it's going through binhex delugevpn container. Thanks in advance.

**Comment by jlesage** [comment]
Why it doesn't work?  Running this on the host should display the assigned IP from the container point-of-view:

```
docker exec <container name> ifconfig
```

**Comment by annualstatement** [comment]
Thanks, that worked.
